#!/bin/sh

if [ ! "$ENVLOADED" ]; then
	if [ -r /etc/rc.conf ]; then
		 . /etc/rc.conf 2> /dev/null
		ENVLOADED="1"
	fi
fi

if [ ! "$CONFIGLOADED" ]; then
	if [ -r /etc/rc.d/config.sh ]; then
		. /etc/rc.d/config.sh 2>/dev/null
		CONFIGLOADED="1"
	fi
fi

if [ "$CONFIG_FEATURE_WIRELESS" = "1" ]; then
    #
    # Determine if the modules are already up.  If so, simply
    # exit without error.
    #

    MODLIST=`cat /proc/modules | grep ath_hal | cut -f1,0 -d" "`
    
    if [ "${MODLIST}" = "ath_hal" ]; then
        echo "AP is already up"
        exit
    fi

    echo 1 > /proc/sys/vm/drop_caches; sleep 1
    sync
    
	cfg -a AP_ENABLE_DL=1
	/etc/rc.d/rc.wlan up
fi
