x_LTQ_Param x_LTQ_Device_param [] = {
	{"Firewall", DEVICE_FIREWALL, LTQ_PARAM_TYPE_STRUCT,
	offsetof(Device_t, pFirewall), NULL, 0},
	{"xParamMap", 0, LTQ_PARAM_TYPE_UINT,
	offsetof(Device_t, xParamMap), NULL, 0},
};

x_LTQ_Param x_LTQ_Firewall_param [] = {
	{"Enable", DEVICE_FIREWALL_ENABLE, LTQ_PARAM_TYPE_BOOL,
	offsetof(Firewall_t, bEnable), NULL, 0},
	{"Config", DEVICE_FIREWALL_CONFIG, LTQ_PARAM_TYPE_ENUM,
	offsetof(Firewall_t, eConfig), FirewallConfig_nv, 4},
	{"AdvancedLevel", DEVICE_FIREWALL_ADVANCEDLEVEL, LTQ_PARAM_TYPE_STR,
	offsetof(Firewall_t, sAdvancedLevel), NULL, 0},
	{"Type", DEVICE_FIREWALL_TYPE, LTQ_PARAM_TYPE_ENUM,
	offsetof(Firewall_t, eType), FirewallType_nv, 2},
	{"Version", DEVICE_FIREWALL_VERSION, LTQ_PARAM_TYPE_STR,
	offsetof(Firewall_t, sVersion), NULL, 0},
	{"Version", DEVICE_FIREWALL_VERSION, LTQ_PARAM_TYPE_STR,
	offsetof(Firewall_t, sVersion), NULL, 0},
	{"LevelNumberOfEntries", DEVICE_FIREWALL_LEVELNUMBEROFENTRIES, LTQ_PARAM_TYPE_UINT,
	offsetof(Firewall_t, unLevelNumberOfEntries), NULL, 0},
	{"ChainNumberOfEntries", DEVICE_FIREWALL_CHAINNUMBEROFENTRIES, LTQ_PARAM_TYPE_UINT,
	offsetof(Firewall_t, unChainNumberOfEntries), NULL, 0},
	{"Level", DEVICE_FIREWALL_LEVEL, LTQ_PARAM_TYPE_STRUCT,
	offsetof(Firewall_t, pFirewall_Level), NULL, 0},
	{"Chain", DEVICE_FIREWALL_CHAIN, LTQ_PARAM_TYPE_STRUCT,
	offsetof(Firewall_t, pFirewall_Chain), NULL, 0},
	{"X_LANTIQ_COM_ParentalControl", DEVICE_FIREWALL_X_LANTIQ_COM_PARENTALCONTROL, LTQ_PARAM_TYPE_STRUCT,
	offsetof(Firewall_t, pFirewall_X_LANTIQ_COM_ParentalControl), NULL, 0},
	{"xParamMap", 0, LTQ_PARAM_TYPE_UINT,
	offsetof(Firewall_t, xParamMap), NULL, 0},
};

x_LTQ_Param x_LTQ_Firewall_Level_param [] = {
	{"Name", DEVICE_FIREWALL_LEVEL_NAME, LTQ_PARAM_TYPE_STR,
	offsetof(Firewall_Level_t, sName), NULL, 0},
	{"Description", DEVICE_FIREWALL_LEVEL_DESCRIPTION, LTQ_PARAM_TYPE_STR,
	offsetof(Firewall_Level_t, sDescription), NULL, 0},
	{"Order", DEVICE_FIREWALL_LEVEL_ORDER, LTQ_PARAM_TYPE_UINT,
	offsetof(Firewall_Level_t, unOrder), NULL, 0},
	{"Chain", DEVICE_FIREWALL_LEVEL_CHAIN, LTQ_PARAM_TYPE_STR,
	offsetof(Firewall_Level_t, sChain), NULL, 0},
	{"PortMappingEnabled", DEVICE_FIREWALL_LEVEL_PORTMAPPINGENABLED, LTQ_PARAM_TYPE_BOOL,
	offsetof(Firewall_Level_t, bPortMappingEnabled), NULL, 0},
	{"DefaultPolicy", DEVICE_FIREWALL_LEVEL_DEFAULTPOLICY, LTQ_PARAM_TYPE_ENUM,
	offsetof(Firewall_Level_t, eDefaultPolicy), NULL, 0},
	{"DefaultLogPolicy", DEVICE_FIREWALL_LEVEL_DEFAULTLOGPOLICY, LTQ_PARAM_TYPE_BOOL,
	offsetof(Firewall_Level_t, bDefaultLogPolicy), NULL, 0},
	{"xParamMap", 0, LTQ_PARAM_TYPE_UINT,
	offsetof(Firewall_Level_t, xParamMap), NULL, 0},
};

x_LTQ_Param x_LTQ_Firewall_Chain_param [] = {
	{"Enable", DEVICE_FIREWALL_CHAIN_ENABLE, LTQ_PARAM_TYPE_BOOL,
	offsetof(Firewall_Chain_t, bEnable), NULL, 0},
	{"Enable", DEVICE_FIREWALL_CHAIN_ENABLE, LTQ_PARAM_TYPE_BOOL,
	offsetof(Firewall_Chain_t, bEnable), NULL, 0},
	{"Name", DEVICE_FIREWALL_CHAIN_NAME, LTQ_PARAM_TYPE_STR,
	offsetof(Firewall_Chain_t, sName), NULL, 0},
	{"Creator", DEVICE_FIREWALL_CHAIN_CREATOR, LTQ_PARAM_TYPE_ENUM,
	offsetof(Firewall_Chain_t, eCreator), Firewall_ChainCreator_nv, 6},
	{"RuleNumberOfEntries", DEVICE_FIREWALL_CHAIN_RULENUMBEROFENTRIES, LTQ_PARAM_TYPE_UINT,
	offsetof(Firewall_Chain_t, unRuleNumberOfEntries), NULL, 0},
	{"Rule", DEVICE_FIREWALL_CHAIN_RULE, LTQ_PARAM_TYPE_STRUCT,
	offsetof(Firewall_Chain_t, pFirewall_Chain_Rule), NULL, 0},
	{"xParamMap", 0, LTQ_PARAM_TYPE_UINT,
	offsetof(Firewall_Chain_t, xParamMap), NULL, 0},
};

x_LTQ_Param x_LTQ_Firewall_Chain_Rule_param [] = {
	{"Enable", DEVICE_FIREWALL_CHAIN_RULE_ENABLE, LTQ_PARAM_TYPE_BOOL,
	offsetof(Firewall_Chain_Rule_t, bEnable), NULL, 0},
	{"Status", DEVICE_FIREWALL_CHAIN_RULE_STATUS, LTQ_PARAM_TYPE_ENUM,
	offsetof(Firewall_Chain_Rule_t, eStatus), Firewall_Chain_RuleStatus_nv, 3},
	{"Order", DEVICE_FIREWALL_CHAIN_RULE_ORDER, LTQ_PARAM_TYPE_UINT,
	offsetof(Firewall_Chain_Rule_t, unOrder), NULL, 0},
	{"Order", DEVICE_FIREWALL_CHAIN_RULE_ORDER, LTQ_PARAM_TYPE_UINT,
	offsetof(Firewall_Chain_Rule_t, unOrder), NULL, 0},
	{"Description", DEVICE_FIREWALL_CHAIN_RULE_DESCRIPTION, LTQ_PARAM_TYPE_STR,
	offsetof(Firewall_Chain_Rule_t, sDescription), NULL, 0},
	{"Target", DEVICE_FIREWALL_CHAIN_RULE_TARGET, LTQ_PARAM_TYPE_ENUM,
	offsetof(Firewall_Chain_Rule_t, eTarget), Firewall_Chain_RuleTarget_nv, 5},
	{"TargetChain", DEVICE_FIREWALL_CHAIN_RULE_TARGETCHAIN, LTQ_PARAM_TYPE_STR,
	offsetof(Firewall_Chain_Rule_t, sTargetChain), NULL, 0},
	{"Log", DEVICE_FIREWALL_CHAIN_RULE_LOG, LTQ_PARAM_TYPE_BOOL,
	offsetof(Firewall_Chain_Rule_t, bLog), NULL, 0},
	{"Log", DEVICE_FIREWALL_CHAIN_RULE_LOG, LTQ_PARAM_TYPE_BOOL,
	offsetof(Firewall_Chain_Rule_t, bLog), NULL, 0},
	{"Log", DEVICE_FIREWALL_CHAIN_RULE_LOG, LTQ_PARAM_TYPE_BOOL,
	offsetof(Firewall_Chain_Rule_t, bLog), NULL, 0},
	{"SourceInterface", DEVICE_FIREWALL_CHAIN_RULE_SOURCEINTERFACE, LTQ_PARAM_TYPE_STR,
	offsetof(Firewall_Chain_Rule_t, sSourceInterface), NULL, 0},
	{"SourceInterfaceExclude", DEVICE_FIREWALL_CHAIN_RULE_SOURCEINTERFACEEXCLUDE, LTQ_PARAM_TYPE_BOOL,
	offsetof(Firewall_Chain_Rule_t, bSourceInterfaceExclude), NULL, 0},
	{"SourceAllInterfaces", DEVICE_FIREWALL_CHAIN_RULE_SOURCEALLINTERFACES, LTQ_PARAM_TYPE_BOOL,
	offsetof(Firewall_Chain_Rule_t, bSourceAllInterfaces), NULL, 0},
	{"DestInterface", DEVICE_FIREWALL_CHAIN_RULE_DESTINTERFACE, LTQ_PARAM_TYPE_STR,
	offsetof(Firewall_Chain_Rule_t, sDestInterface), NULL, 0},
	{"DestInterfaceExclude", DEVICE_FIREWALL_CHAIN_RULE_DESTINTERFACEEXCLUDE, LTQ_PARAM_TYPE_BOOL,
	offsetof(Firewall_Chain_Rule_t, bDestInterfaceExclude), NULL, 0},
	{"DestAllInterfaces", DEVICE_FIREWALL_CHAIN_RULE_DESTALLINTERFACES, LTQ_PARAM_TYPE_BOOL,
	offsetof(Firewall_Chain_Rule_t, bDestAllInterfaces), NULL, 0},
	{"DestAllInterfaces", DEVICE_FIREWALL_CHAIN_RULE_DESTALLINTERFACES, LTQ_PARAM_TYPE_BOOL,
	offsetof(Firewall_Chain_Rule_t, bDestAllInterfaces), NULL, 0},
	{"DestAllInterfaces", DEVICE_FIREWALL_CHAIN_RULE_DESTALLINTERFACES, LTQ_PARAM_TYPE_BOOL,
	offsetof(Firewall_Chain_Rule_t, bDestAllInterfaces), NULL, 0},
	{"DestAllInterfaces", DEVICE_FIREWALL_CHAIN_RULE_DESTALLINTERFACES, LTQ_PARAM_TYPE_BOOL,
	offsetof(Firewall_Chain_Rule_t, bDestAllInterfaces), NULL, 0},
	{"DestIPExclude", DEVICE_FIREWALL_CHAIN_RULE_DESTIPEXCLUDE, LTQ_PARAM_TYPE_BOOL,
	offsetof(Firewall_Chain_Rule_t, bDestIPExclude), NULL, 0},
	{"DestIPExclude", DEVICE_FIREWALL_CHAIN_RULE_DESTIPEXCLUDE, LTQ_PARAM_TYPE_BOOL,
	offsetof(Firewall_Chain_Rule_t, bDestIPExclude), NULL, 0},
	{"DestIPExclude", DEVICE_FIREWALL_CHAIN_RULE_DESTIPEXCLUDE, LTQ_PARAM_TYPE_BOOL,
	offsetof(Firewall_Chain_Rule_t, bDestIPExclude), NULL, 0},
	{"SourceIPExclude", DEVICE_FIREWALL_CHAIN_RULE_SOURCEIPEXCLUDE, LTQ_PARAM_TYPE_BOOL,
	offsetof(Firewall_Chain_Rule_t, bSourceIPExclude), NULL, 0},
	{"SourceIPExclude", DEVICE_FIREWALL_CHAIN_RULE_SOURCEIPEXCLUDE, LTQ_PARAM_TYPE_BOOL,
	offsetof(Firewall_Chain_Rule_t, bSourceIPExclude), NULL, 0},
	{"ProtocolExclude", DEVICE_FIREWALL_CHAIN_RULE_PROTOCOLEXCLUDE, LTQ_PARAM_TYPE_BOOL,
	offsetof(Firewall_Chain_Rule_t, bProtocolExclude), NULL, 0},
	{"ProtocolExclude", DEVICE_FIREWALL_CHAIN_RULE_PROTOCOLEXCLUDE, LTQ_PARAM_TYPE_BOOL,
	offsetof(Firewall_Chain_Rule_t, bProtocolExclude), NULL, 0},
	{"ProtocolExclude", DEVICE_FIREWALL_CHAIN_RULE_PROTOCOLEXCLUDE, LTQ_PARAM_TYPE_BOOL,
	offsetof(Firewall_Chain_Rule_t, bProtocolExclude), NULL, 0},
	{"DestPortExclude", DEVICE_FIREWALL_CHAIN_RULE_DESTPORTEXCLUDE, LTQ_PARAM_TYPE_BOOL,
	offsetof(Firewall_Chain_Rule_t, bDestPortExclude), NULL, 0},
	{"DestPortExclude", DEVICE_FIREWALL_CHAIN_RULE_DESTPORTEXCLUDE, LTQ_PARAM_TYPE_BOOL,
	offsetof(Firewall_Chain_Rule_t, bDestPortExclude), NULL, 0},
	{"DestPortExclude", DEVICE_FIREWALL_CHAIN_RULE_DESTPORTEXCLUDE, LTQ_PARAM_TYPE_BOOL,
	offsetof(Firewall_Chain_Rule_t, bDestPortExclude), NULL, 0},
	{"SourcePortExclude", DEVICE_FIREWALL_CHAIN_RULE_SOURCEPORTEXCLUDE, LTQ_PARAM_TYPE_BOOL,
	offsetof(Firewall_Chain_Rule_t, bSourcePortExclude), NULL, 0},
	{"SourcePortExclude", DEVICE_FIREWALL_CHAIN_RULE_SOURCEPORTEXCLUDE, LTQ_PARAM_TYPE_BOOL,
	offsetof(Firewall_Chain_Rule_t, bSourcePortExclude), NULL, 0},
	{"DSCPExclude", DEVICE_FIREWALL_CHAIN_RULE_DSCPEXCLUDE, LTQ_PARAM_TYPE_BOOL,
	offsetof(Firewall_Chain_Rule_t, bDSCPExclude), NULL, 0},
	{"X_LANTIQ_COM_FIREWALL_MACAddress", DEVICE_FIREWALL_CHAIN_RULE_X_LANTIQ_COM_FIREWALL_MACADDRESS, LTQ_PARAM_TYPE_STR,
	offsetof(Firewall_Chain_Rule_t, sX_LANTIQ_COM_FIREWALL_MACAddress), NULL, 0},
	{"xParamMap", 0, LTQ_PARAM_TYPE_UINT,
	offsetof(Firewall_Chain_Rule_t, xParamMap), NULL, 0},
};

x_LTQ_Param x_LTQ_Firewall_X_LANTIQ_COM_ParentalControl_param [] = {
	{"Enable", DEVICE_FIREWALL_X_LANTIQ_COM_PARENTALCONTROL_ENABLE, LTQ_PARAM_TYPE_BOOL,
	offsetof(Firewall_X_LANTIQ_COM_ParentalControl_t, bEnable), NULL, 0},
	{"DefaultAction", DEVICE_FIREWALL_X_LANTIQ_COM_PARENTALCONTROL_DEFAULTACTION, LTQ_PARAM_TYPE_BOOL,
	offsetof(Firewall_X_LANTIQ_COM_ParentalControl_t, bDefaultAction), NULL, 0},
	{"RuleNumberOfEntries", DEVICE_FIREWALL_X_LANTIQ_COM_PARENTALCONTROL_RULENUMBEROFENTRIES, LTQ_PARAM_TYPE_UINT,
	offsetof(Firewall_X_LANTIQ_COM_ParentalControl_t, unRuleNumberOfEntries), NULL, 0},
	{"Rule", DEVICE_FIREWALL_X_LANTIQ_COM_PARENTALCONTROL_RULE, LTQ_PARAM_TYPE_STRUCT,
	offsetof(Firewall_X_LANTIQ_COM_ParentalControl_t, pFirewall_X_LANTIQ_COM_ParentalControl_Rule), NULL, 0},
	{"xParamMap", 0, LTQ_PARAM_TYPE_UINT,
	offsetof(Firewall_X_LANTIQ_COM_ParentalControl_t, xParamMap), NULL, 0},
};

x_LTQ_Param x_LTQ_Firewall_X_LANTIQ_COM_ParentalControl_Rule_param [] = {
	{"Enable", DEVICE_FIREWALL_X_LANTIQ_COM_PARENTALCONTROL_RULE_ENABLE, LTQ_PARAM_TYPE_BOOL,
	offsetof(Firewall_X_LANTIQ_COM_ParentalControl_Rule_t, bEnable), NULL, 0},
	{"Target", DEVICE_FIREWALL_X_LANTIQ_COM_PARENTALCONTROL_RULE_TARGET, LTQ_PARAM_TYPE_ENUM,
	offsetof(Firewall_X_LANTIQ_COM_ParentalControl_Rule_t, eTarget), Firewall_X_LANTIQ_COM_ParentalControl_RuleTarget_nv, 5},
	{"MACAddress", DEVICE_FIREWALL_X_LANTIQ_COM_PARENTALCONTROL_RULE_MACADDRESS, LTQ_PARAM_TYPE_STR,
	offsetof(Firewall_X_LANTIQ_COM_ParentalControl_Rule_t, sMACAddress), NULL, 0},
	{"TimeStart", DEVICE_FIREWALL_X_LANTIQ_COM_PARENTALCONTROL_RULE_TIMESTART, LTQ_PARAM_TYPE_STR,
	offsetof(Firewall_X_LANTIQ_COM_ParentalControl_Rule_t, sTimeStart), NULL, 0},
	{"TimeEnd", DEVICE_FIREWALL_X_LANTIQ_COM_PARENTALCONTROL_RULE_TIMEEND, LTQ_PARAM_TYPE_STR,
	offsetof(Firewall_X_LANTIQ_COM_ParentalControl_Rule_t, sTimeEnd), NULL, 0},
	{"DaysOfTheWeek", DEVICE_FIREWALL_X_LANTIQ_COM_PARENTALCONTROL_RULE_DAYSOFTHEWEEK, LTQ_PARAM_TYPE_STR,
	offsetof(Firewall_X_LANTIQ_COM_ParentalControl_Rule_t, sDaysOfTheWeek), NULL, 0},
	{"xParamMap", 0, LTQ_PARAM_TYPE_UINT,
	offsetof(Firewall_X_LANTIQ_COM_ParentalControl_Rule_t, xParamMap), NULL, 0},
};

