#!/bin/sh

if [ ! "$ENVLOADED" ]; then
	if [ -r /etc/rc.conf ]; then
		 . /etc/rc.conf 2> /dev/null
		ENVLOADED="1"
	fi
fi

if [ ! "$CONFIGLOADED" ]; then
	if [ -r /etc/rc.d/config.sh ]; then
		. /etc/rc.d/config.sh 2>/dev/null
		CONFIGLOADED="1"
	fi
fi

RA_IF=""
find_ra_if_from_index() {
   eval CPEID='$'wlmn_${1}'_cpeId'
   ra_dev=`/usr/sbin/status_oper GET "RA_MAP" "$CPEID"`
   RA_IF=${ra_dev:2}
   #echo "ATH_IF $ATH_IF "
}

find_ra_if_from_index $1

if [ "$CONFIG_FEATURE_WIRELESS" = "1" ]; then
   # interface down

   echo "ralink_inf_idx is ${RA_IF}"

   #Invoked with index args i.e.  wlan_vap_remove 1 (index 1 or 2 only. For VAP ra1 and ra2)

   #Virtual interface down
   /usr/sbin/brctl delif br0 ra${RA_IF}
      /sbin/ifconfig ra${RA_IF} down
      WscdPid=`cat  /var/run/wscd.pid.ra${RA_IF}`
      kill -9 $WscdPid
fi
