#!/bin/sh



if [ ! "$ENVLOADED" ]; then
	if [ -r /etc/rc.conf ]; then
		 . /etc/rc.conf 2> /dev/null
		ENVLOADED="1"
	fi
fi

if [ ! "$CONFIGLOADED" ]; then
	if [ -r /etc/rc.d/config.sh ]; then
		. /etc/rc.d/config.sh 2>/dev/null
		CONFIGLOADED="1"
	fi
fi

RA_IF=""
find_ra_if_from_index() {
   eval CPEID='$'wlmn_${1}'_cpeId'
   ra_dev=`/usr/sbin/status_oper GET "RA_MAP" "$CPEID"`
   RA_IF=${ra_dev:2}
}
find_ra_if_from_index $1

echo "hsur current ralink_inf_idx is ${RA_IF}"

if [ "$CONFIG_FEATURE_WIRELESS" = "1" ]; then
	TEMP_FILE="/ramdisk/tmp/wsc_status"
	
	iwpriv ra${RA_IF} ar9_show get_wsc_status > ${TEMP_FILE}
	
   
fi
