#!/bin/sh
# Prepare Wave environment and initiate Wave drivers
# Needed object: Radio.Vendor

script_name="$0"

if [ -e /opt/lantiq/wave/scripts/fapi_wlan_wave_lib_common.sh ]
then
	. /opt/lantiq/wave/scripts/fapi_wlan_wave_lib_common.sh
elif [ -e /etc/wave/scripts/fapi_wlan_wave_lib_common.sh ]
then
	. /etc/wave/scripts/fapi_wlan_wave_lib_common.sh
fi

mkdir -p $CONF_DIR

# DEBUG: set debug_save_conf in fapi_wlan_wave_lib_common.sh to save the in conf file
[ "$debug_save_conf" ] && cp ${IN_CONF} ${CONF_DIR}/hw_init_in_conf

# Save the input configuration parameters to a local DB used by Wave FAPI and source it
save_db_params hw_init
local_db_source RADIO
# Radio vendor updated object parameters will be saved during radio_set, delete the radio conf file
rm -f $RADIO_CONF

timestamp 0 "$script_name:begin"
print2log 0 DEBUG "$script_name $*"

# Set the init flag to indicate init sequence is in progress
touch $INIT_FLAG

eeprom_partition=wlanconfig
eeprom_tar=eeprom.tar.gz

# Source config.sh on UGW:
[ -e /etc/rc.d/config.sh ] && . /etc/rc.d/config.sh

# The object indexes in the in.conf file are 0 for the first radio and 1 for the second radio (always)
radio0_vendor_index=0
radio1_vendor_index=1
next_object_index=2

# driver_mode can be ap or dut
driver_mode=$1
[ -z "$driver_mode" ] && driver_mode="ap"

# Create softlinks for library functions
cp -s ${ETC_PATH}/fapi_wlan_wave_lib* /tmp/

# Delete the runner file
rm -f ${CONF_DIR}/${FAPI_WLAN_WAVE_RUNNNER}

# Count number of physical WAVE interfaces
# Read information of physical Wlan interface from wlan_discover output
(. ${ETC_PATH}/fapi_wlan_wave_discover.sh)
. ${CONF_DIR}/fapi_wlan_wave_discover.txt
wave_count=$((PCI_LTQ_COUNT+AHB_WLAN_COUNT))

# No Wave interfaces were found, print error and exit script.
if [ "$wave_count" = "0" ]
then
	print2log 0 ERROR "$script_name: No WAVE interfaces found"
	echo "$script_name: No WAVE interfaces found" >> ${CONF_DIR}/${FAPI_WLAN_WAVE_RUNNNER}
	rm -f $INIT_FLAG
	exit 1
fi

# Save indexes used in the DB for each radio
i=0
while [ $i -lt $wave_count ]
do
	echo "wlan${i}_index=$i" >> $INTERFACES_INDEXES
	i=$((i+1))
done
echo "next_interface_index=$i" >> $INTERFACES_INDEXES
. $INTERFACES_INDEXES

echo "cd /tmp" >> ${CONF_DIR}/${FAPI_WLAN_WAVE_RUNNNER}

# Create softlinks needed in /tmp
echo "cp -s ${DRIVER_PATH}/mtlkroot.ko /tmp/" >> ${CONF_DIR}/${FAPI_WLAN_WAVE_RUNNNER}
echo "cp -s ${BINDIR}/fw_scd_file.scd /tmp/" >> ${CONF_DIR}/${FAPI_WLAN_WAVE_RUNNNER}
echo "cp -s ${BINDIR}/hw_scd_file.scd /tmp/" >> ${CONF_DIR}/${FAPI_WLAN_WAVE_RUNNNER}
echo "cp -s ${DRIVER_PATH}/mtlk.ko /tmp/" >> ${CONF_DIR}/${FAPI_WLAN_WAVE_RUNNNER}
echo "cp -s ${IMAGES_PATH}/* /tmp/" >> ${CONF_DIR}/${FAPI_WLAN_WAVE_RUNNNER}

# Yocto read-only workaround: override files if they exist in /nvram/etc/wave_overlay folder
echo "if [ -d /nvram/etc/wave_overlay ]" >> ${CONF_DIR}/${FAPI_WLAN_WAVE_RUNNNER}
echo "then" >> ${CONF_DIR}/${FAPI_WLAN_WAVE_RUNNNER}
echo "	for f in /nvram/etc/wave_overlay/*" >> ${CONF_DIR}/${FAPI_WLAN_WAVE_RUNNNER}
echo "	do" >> ${CONF_DIR}/${FAPI_WLAN_WAVE_RUNNNER}
echo "		echo \"NOTE:  Overriding  \${f#/nvram/etc/wave_overlay/}\" with file from wave_overlay" >> ${CONF_DIR}/${FAPI_WLAN_WAVE_RUNNNER}
echo "		cp -s \$f /tmp" >> ${CONF_DIR}/${FAPI_WLAN_WAVE_RUNNNER}
echo "	done" >> ${CONF_DIR}/${FAPI_WLAN_WAVE_RUNNNER}
echo "fi" >> ${CONF_DIR}/${FAPI_WLAN_WAVE_RUNNNER}

# Use the ls.txt file to load files to /tmp if the wave_wlan_debug_ls_txt.sh script exists.
[ -e "${ETC_PATH}/fapi_wlan_wave_debug_tftp_bins.sh" ] && (. ${ETC_PATH}/fapi_wlan_wave_debug_tftp_bins.sh)

# Configure Hotplug
echo "echo ${SBINDIR}/hotplug > /proc/sys/kernel/hotplug" >> ${CONF_DIR}/${FAPI_WLAN_WAVE_RUNNNER}

# Start udevd and call crda once, for triggering regulatory domain change notifications
# The crda calls should be done only once on the first init. Using flag to detect first init.
echo "udevd_up=\`ps | grep -c udevd\`" >> ${CONF_DIR}/${FAPI_WLAN_WAVE_RUNNNER}
echo "[ \$udevd_up -gt 1 ] || udevd --daemon" >> ${CONF_DIR}/${FAPI_WLAN_WAVE_RUNNNER}
if [ ! -e $CRDA_FLAG ]
then
	echo "export COUNTRY=00" >> ${CONF_DIR}/${FAPI_WLAN_WAVE_RUNNNER}
	echo "crda" >> ${CONF_DIR}/${FAPI_WLAN_WAVE_RUNNNER}
	echo "touch $CRDA_FLAG" >> ${CONF_DIR}/${FAPI_WLAN_WAVE_RUNNNER}
fi

# insmod rtlogoer
echo "insmod mtlkroot.ko" >> ${CONF_DIR}/${FAPI_WLAN_WAVE_RUNNNER}
# TODO: add check for insmod success.
# Set MAC address to the logger interface and add it to the bridge
# TODO: currently moved to the start sequence, needs to be moved back to init
#echo "ifconfig rtlog0 hw ether 00:00:00:00:00:00" >> ${CONF_DIR}/${FAPI_WLAN_WAVE_RUNNNER}
#echo "brctl addif br-lan rtlog0" >> ${CONF_DIR}/${FAPI_WLAN_WAVE_RUNNNER}
#echo "ifconfig rtlog0 up" >> ${CONF_DIR}/${FAPI_WLAN_WAVE_RUNNNER}
# Create the logger streams
#i=0
#while [ $i -lt $wave_count ]
#do
#	(. $ETC_PATH/wave_wlan_logger_modify $i init)
#      i=$((i+1))
#done
# Load logserver (if exists)
if [ -e ${BINDIR}/logserver ]
then
	echo "cp -s ${BINDIR}/logserver /tmp/" >> ${CONF_DIR}/${FAPI_WLAN_WAVE_RUNNNER}
	echo "/tmp/logserver -f /tmp/dev/mtlkroot0 -s /tmp/fw_scd_file.scd &" >> ${CONF_DIR}/${FAPI_WLAN_WAVE_RUNNNER}
fi

# Get calibration file from FLASH only if file doesn't already exist in /tmp/
# Support Puma (/nvram/etc), Havenpark (/nvram) and UGW read_img
echo "if [ ! -e /tmp/cal_wlan0.bin ]" >> ${CONF_DIR}/${FAPI_WLAN_WAVE_RUNNNER}
echo "then" >> ${CONF_DIR}/${FAPI_WLAN_WAVE_RUNNNER}
if [ -d /nvram/etc/wave_cal ]
then
	# Command to copy cal_wlan files for PUMA
	echo "	cp /nvram/etc/wave_cal/* /tmp/" >> ${CONF_DIR}/${FAPI_WLAN_WAVE_RUNNNER}
elif [ -d /nvram ]
then
	echo "	tar xzf /nvram/$eeprom_tar -C /tmp/" >> ${CONF_DIR}/${FAPI_WLAN_WAVE_RUNNNER}
else
	# Commands to get cal_wlan files from FLASH in UGW
	echo "	read_img $eeprom_partition /tmp/$eeprom_tar" >> ${CONF_DIR}/${FAPI_WLAN_WAVE_RUNNNER}
	echo "	tar xzf /tmp/$eeprom_tar -C /tmp/" >> ${CONF_DIR}/${FAPI_WLAN_WAVE_RUNNNER}
fi
# TODO: add verification for calibration extract success.
echo "fi" >> ${CONF_DIR}/${FAPI_WLAN_WAVE_RUNNNER}

# Insmod WAVE driver
# fastpath enables/disables GSWIP usage. Needed only for GRX350.
fastpath_cmd=""
fastpath0=""
fastpath1=""
disable_fastpath0=""
disable_fastpath1=""

fastpath0=`db2fapi_convert boolean WaveFastpathEnabled $wlan0_index`
[ "$wave_count" = "2" ] && fastpath1=`db2fapi_convert boolean WaveFastpathEnabled $wlan1_index`

# If platform is not GRX350, don't set fastpath command and disable fastpath
if [ "$CONFIG_IFX_CONFIG_CPU" != "GRX500" ]
then
	disable_fastpath0=1
	disable_fastpath1=1
else
	# If AHB is enabled, wlan0 doesn't support fastpath
	[ "$AHB_WLAN_COUNT" = "1" ] && fastpath0=0 && disable_fastpath0=1

	if [ "$wave_count" = "2" ]
	then
		# GRX350 A21 supports fastpath on 2 interfaces
		# GRX350 A11 supports fastpath on 1 interface
		# Check if platform is GRX350 A11 with 2 interfaces with fastpath enabled, if so, set wlan0 to fastpath disabled
		[ "$CONFIG_PACKAGE_KMOD_GRX500_A21" != "1" ] && [ "$fastpath0" = "1" ] && [ "$fastpath1" = "1" ] && fastpath0=0 && disable_fastpath0=1
		fastpath1=",${fastpath1}"
	fi
	fastpath_cmd="fastpath=${fastpath0}${fastpath1}"
	fastpath1=${fastpath1/,/}
fi

# If AHB is not used (2 PCIe cards are connected), set ahb_off flag
ahb_off_cmd=""
[ $AHB_WLAN_COUNT = 0 ] && ahb_off_cmd="ahb_off=1"
if [ $wave_count = 1 ]
then
	print2log $wlan0_index DEBUG "$script_name: insmod command: insmod mtlk.ko $driver_mode=1 $fastpath_cmd $ahb_off_cmd"
	echo "insmod mtlk.ko $driver_mode=1 $fastpath_cmd $ahb_off_cmd" >> ${CONF_DIR}/${FAPI_WLAN_WAVE_RUNNNER}
else
	print2log $wlan0_index DEBUG "$script_name: insmod command: insmod mtlk.ko $driver_mode=1,1 $fastpath_cmd $ahb_off_cmd"
	echo "insmod mtlk.ko $driver_mode=1,1 $fastpath_cmd $ahb_off_cmd" >> ${CONF_DIR}/${FAPI_WLAN_WAVE_RUNNNER}
fi
# TODO: add check for insmod success.
echo "cd - > /dev/null" >> ${CONF_DIR}/${FAPI_WLAN_WAVE_RUNNNER}

# Init HS2.0 related drivers
[ -e ${ETC_PATH}/wave_wifi_parp_ctrl.sh ] && echo "(. ${ETC_PATH}/wave_wifi_parp_ctrl.sh start)" >> ${CONF_DIR}/${FAPI_WLAN_WAVE_RUNNNER}
[ -e ${ETC_PATH}/wave_wifi_l2f_ctrl.sh ] && echo "(. ${ETC_PATH}/wave_wifi_l2f_ctrl.sh start)" >> ${CONF_DIR}/${FAPI_WLAN_WAVE_RUNNNER}

# UGW WORKAROUND: remove wlan interfaces from udev rules (in Yocto this is handled at build time in 80-net-setup-link.rules)
if [ -e /etc/udev/rules.d/70-persistent-net.rules ]
then
	echo "grep -v wlan /etc/udev/rules.d/70-persistent-net.rules > ${CONF_DIR}/tmp_70-persistent-net.rules" >> ${CONF_DIR}/${FAPI_WLAN_WAVE_RUNNNER}
	echo "mv ${CONF_DIR}/tmp_70-persistent-net.rules /etc/udev/rules.d/70-persistent-net.rules" >> ${CONF_DIR}/${FAPI_WLAN_WAVE_RUNNNER}
fi

# Execute the runner
chmod +x ${CONF_DIR}/${FAPI_WLAN_WAVE_RUNNNER}
${CONF_DIR}/${FAPI_WLAN_WAVE_RUNNNER}

# DEBUG: set debug_save_runner in fapi_wlan_wave_lib_common.sh to save the runner script
[ "$debug_save_runner" ] && cp ${CONF_DIR}/${FAPI_WLAN_WAVE_RUNNNER} ${CONF_DIR}/runner_hw_init.sh

# Create the output configuration file
cat /dev/null > ${OUT_CONF}

update_conf_out "Object_0" "${RADIO_VENDOR_OBJECT}"
[ "$disable_fastpath0" ] && update_conf_out "WaveFastpathEnabled_0" "false" && save_hw_init_out wlan0 0 "WaveFastpathEnabled" "false"

# Read number of antennas from driver
driver_num_of_antennas=`get_driver_num_of_antennas wlan0`

# Set number of antennas, BF-ANTENNA and SOUNDING-DIMENSION from driver to XML
num_antennas_db=`db2fapi_convert regular NumOfAntennas $wlan0_index`
bf_antenna_db=`db2fapi_convert regular VhtBfAntenna $wlan0_index`
sounding_dimension_db=`db2fapi_convert regular VhtSoundingDimension $wlan0_index`
if [ "$driver_num_of_antennas" ]
then
	# Check if need to update DB with new values
	[ $driver_num_of_antennas -lt $num_antennas_db ] && antennas_to_set="$driver_num_of_antennas"
	[ $driver_num_of_antennas -lt $bf_antenna_db ] && vht_bf_antenna_to_set="$driver_num_of_antennas"
	[ $driver_num_of_antennas -lt $sounding_dimension_db ] && vht_sounding_to_set="$driver_num_of_antennas"

	[ -n "$antennas_to_set" ] && update_conf_out "NumOfAntennas_0" "$antennas_to_set" && save_hw_init_out wlan0 0 "NumOfAntennas" "$antennas_to_set"
	[ -n "$vht_bf_antenna_to_set" ] && update_conf_out "VhtBfAntenna_0" "$vht_bf_antenna_to_set" && save_hw_init_out wlan0 0 "VhtBfAntenna" "$vht_bf_antenna_to_set"
	[ -n "$vht_sounding_to_set" ] && update_conf_out "VhtSoundingDimension_0" "$vht_sounding_to_set" && save_hw_init_out wlan0 0 "VhtSoundingDimension" "$vht_sounding_to_set"
fi

# Read driver capability for beamforming.
# If driver doesn't support beamforming, set explicit beamforming, implicit beamforming and vht beamforming disabled
beamforming_support=`iwpriv wlan0 gBfExplicitCap`
beamforming_support=`echo ${beamforming_support##w*:}`
if [ "$beamforming_support" = "0" ]
then
	update_conf_out "WaveExplicitBeamforming_0" "false" && save_hw_init_out wlan0 0 "WaveExplicitBeamforming" "false"
	update_conf_out "WaveImplicitBeamforming_0" "false" && save_hw_init_out wlan0 0 "WaveImplicitBeamforming" "false"
	update_conf_out "VhtSUbeamformerEnabled_0" "false" && save_hw_init_out wlan0 0 "VhtSUbeamformerEnabled" "false"
fi

# Set AutoCoC disabled for fastpath enabled interface. Only for GRX350
[ "$CONFIG_IFX_CONFIG_CPU" = "GRX500" ] && [ "$fastpath0" = "1" ] && update_conf_out "AutoCocEnabled_0" "false" && save_hw_init_out wlan0 0 "AutoCocEnabled" "false"

# TEMPORARY WORKAROUND: set fast and full recovery disabled for Wave500
if [ $AHB_WLAN_COUNT = 0 ] && [ $PCI_LTQ_COUNT -gt 0 ]
then
	update_conf_out "WaveFastRecoveryEnabled_0" "false" && save_hw_init_out wlan0 0 "WaveFastRecoveryEnabled" "false"
	update_conf_out "WaveFullRecoveryEnabled_0" "false" && save_hw_init_out wlan0 0 "WaveFullRecoveryEnabled" "false"
fi

# If 2 interfaces exist, update parameters for wlan1
if [ "$wave_count" = "2" ]
then
	update_conf_out "Object_1" "${RADIO_VENDOR_OBJECT}"
	[ "$disable_fastpath1" ] && update_conf_out "WaveFastpathEnabled_1" "false" && save_hw_init_out wlan1 1 "WaveFastpathEnabled" "false"

	# Read number of antennas from driver
	driver_num_of_antennas1=`get_driver_num_of_antennas wlan1`

	# Set number of antennas, BF-ANTENNA and SOUNDING-DIMENSION from driver to XML
	num_antennas_db1=`db2fapi_convert regular NumOfAntennas $wlan1_index`
	bf_antenna_db1=`db2fapi_convert regular VhtBfAntenna $wlan1_index`
	sounding_dimension_db1=`db2fapi_convert regular VhtSoundingDimension $wlan1_index`
	if [ "$driver_num_of_antennas1" ]
	then
		# Check if need to update DB with new values
		[ $driver_num_of_antennas1 -lt $num_antennas_db1 ] && antennas_to_set1="$driver_num_of_antennas1"
		[ $driver_num_of_antennas1 -lt $bf_antenna_db1 ] && vht_bf_antenna_to_set1="$driver_num_of_antennas1"
		[ $driver_num_of_antennas1 -lt $sounding_dimension_db1 ] && vht_sounding_to_set1="$driver_num_of_antennas1"

		[ -n "$antennas_to_set1" ] && update_conf_out "NumOfAntennas_1" "$antennas_to_set1" && save_hw_init_out wlan1 1 "NumOfAntennas" "$antennas_to_set1"
		[ -n "$vht_bf_antenna_to_set1" ] && update_conf_out "VhtBfAntenna_1" "$vht_bf_antenna_to_set1" && save_hw_init_out wlan1 1 "VhtBfAntenna" "$vht_bf_antenna_to_set1"
		[ -n "$vht_sounding_to_set1" ] && update_conf_out "VhtSoundingDimension_1" "$vht_sounding_to_set1" && save_hw_init_out wlan1 1 "VhtSoundingDimension" "$vht_sounding_to_set1"
	fi

	# Read driver capability for beamforming.
	# If driver doesn't support beamforming, set explicit beamforming, implicit beamforming and vht beamforming disabled
	beamforming_support1=`iwpriv wlan1 gBfExplicitCap`
	beamforming_support1=`echo ${beamforming_support1##w*:}`
	if [ "$beamforming_support1" = "0" ]
	then
		update_conf_out "WaveExplicitBeamforming_1" "false" && save_hw_init_out wlan1 1 "WaveExplicitBeamforming" "false"
		update_conf_out "WaveImplicitBeamforming_1" "false" && save_hw_init_out wlan1 1 "WaveImplicitBeamforming" "false"
		update_conf_out "VhtSUbeamformerEnabled_1" "false" && save_hw_init_out wlan1 1 "VhtSUbeamformerEnabled" "false"
	fi

	# Set AutoCoC disabled for fastpath enabled interface. Only for GRX350
	[ "$CONFIG_IFX_CONFIG_CPU" = "GRX500" ] && [ "$fastpath1" = "1" ] && update_conf_out "AutoCocEnabled_1" "false" && save_hw_init_out wlan1 1 "AutoCocEnabled" "false"

	# TEMPORARY WORKAROUND: set fast and full recovery disabled for Wave500
	update_conf_out "WaveFastRecoveryEnabled_1" "false" && save_hw_init_out wlan1 1 "WaveFastRecoveryEnabled" "false"
	update_conf_out "WaveFullRecoveryEnabled_1" "false" && save_hw_init_out wlan1 1 "WaveFullRecoveryEnabled" "false"
fi

# Map indexes for the objects to return:
# wifi, radio for wlan0
wifi_index=$next_object_index
next_object_index=$((next_object_index+1))
radio_index=$next_object_index
next_object_index=$((next_object_index+1))

# Update number of Radio interfaces created
update_conf_out "Object_${wifi_index}" "$WIFI_OBJECT"
update_conf_out "RadioNumberOfEntries_${wifi_index}" "$wave_count"

# Read country from EEPROM
country_code=`iwpriv wlan0 gEEPROM`
country_code=`echo "$eeprom" | sed -n '/EEPROM country:/{s/EEPROM country:.*\([A-Z?][A-Z?]\)/\1/p}'`

# Update the names of the interfaces created
# Workaround to reverse order of interfaces returned to SL on Haven Park Platform
# (wlan1 is 2.4GHz and wlan0 is 5GHz)
IS_HAVEN_PARK=`cat /proc/cmdline | grep -c BoardID=0xE6`
if [ $IS_HAVEN_PARK -eq 0 ]
then
	# Read the names of the interfaces created
	interfaces_created=`ls /proc/net/mtlk | grep wlan`
	for interface in $interfaces_created
	do
		update_conf_out "Object_${radio_index}" "${RADIO_OBJECT}${radio_index}"
		update_conf_out "Name_${radio_index}" "$interface"
		# Update regulatory domain only if country is set in the EEPROM
		[ -n "$country_code" ] && [ "$country_code" != "??" ] && update_conf_out "RegulatoryDomain_${radio_index}" "$country_code"
		radio_index=$next_object_index
		next_object_index=$((next_object_index+1))
	done
else
	# Haven Park --> Use fixed order of interface names
	echo fapi_wlan_wave_hw_init: HAVEN PARK DETECTED - USING wlan1 as first configured interface > /dev/console
	update_conf_out "Object_${radio_index}" "${RADIO_OBJECT}${radio_index}"
	update_conf_out "Name_${radio_index}" "wlan1"
	radio_index=$next_object_index
	update_conf_out "Object_${radio_index}" "${RADIO_OBJECT}${radio_index}"
	update_conf_out "Name_${radio_index}" "wlan0"
fi

# Configuration is completed successfully
update_conf_out "wlan_configuration_status" "success"

# DEBUG: set debug_save_conf in fapi_wlan_wave_lib_common.sh to save the out conf file
[ "$debug_save_conf" ] && cp ${OUT_CONF} ${CONF_DIR}/hw_init_out_conf

print2log $wlan0_index DEBUG "$script_name done"
timestamp $wlan0_index "$script_name:done"
