#!/bin/sh

if [ ! "$CONFIGLOADED" ]; then
	if [ -r /etc/rc.d/config.sh ]; then
		. /etc/rc.d/config.sh 2>/dev/null
		CONFIGLOADED="1"
	fi
fi

if [ "$CONFIG_FEATURE_WIRELESS" = "1" ]; then # [
	echo "vendor=\"Ralink\""
	echo "standard=\"0,2,3,4,5,6\""
	echo "freq=\"0,1\""
	echo "powerLvl=\"20,40,60,80,100\""
	echo "security=\"3\""
	echo "radius=\"0\""
	echo "WMM=\"1\""
	echo "UAPSD=\"1\""
	echo "WPS=\"1\""
	echo "WPS_CfgMethods=\"3,4,8,9\""
	echo "WDS=\"1\""
	echo "WDS_RepCount=\"0\""
	echo "maxVAP=\"8\""
	echo "maxClientsPerVAP=\"16\""
	echo "macAddrCntrlPerVAP=\"1\""
	echo "numMACCntrlEntries=\"8\""
	echo "numRxAntenna=\"2\""
	echo "numTxAntenna=\"2\""
	echo "wideChanSupport=\"1\""
	echo "MCSrange=\"15\""
	echo "AMPDUsupport=\"1\""
	echo "AMSDUsupport=\"1\""	
fi # ]
	
