#!/bin/sh

# Defines
if [ ! "$MTLK_INIT_PLATFORM" ]; then
        . /tmp/mtlk_init_platform.sh
fi

print2log DBG "running wave_wlan_get_dyn_wan_info, args: $*"	

apIndex=$1

timestamp "wave_wlan_get_dyn_wan_info:$apIndex:begin"

# Get corresponding wlan network interface from mapping file
wlan=`find_wave_if_from_index $apIndex`

data=`$ETC_PATH/wmdctrl.sh $wlan get`
echo "$data"

print2log DBG "wave_wlan_get_dyn_wan_info done"
timestamp "wave_wlan_get_dyn_wan_info:$apIndex:done"

