#!/bin/sh
if [ ! "$CONFIGLOADED" ]; then
        if [ -r /etc/config.sh ]; then
                . /etc/config.sh 2>/dev/null
                CONFIGLOADED="1"
        fi
fi

. /etc/switchports.conf 2> /dev/null
. /etc/init.d/switch_functions $3 2> /dev/null

# This script takes wan vlan id as input argument and configures VLANs
# in switch. This script calls functions defined in
# /etc/init.d/switch_functions

operation=$1
wan_vid=$2
Egress_tag=1

echo "wan vlan config $1 called for vlan $2"
if [ "$1" = "1" ]; then
	create_vlanid $wan_vid $wan_fid
	config_port_member $wan_vid $cpu_port $Egress_tag
	for i in $wan_port; do
	  config_port_member $wan_vid $i $Egress_tag
	done
elif [ "$1" = "0" ]; then
	for i in $wan_port; do
	  reset_port_member $wan_vid $wan_port $Egress_tag
	done
	reset_port_member $wan_vid $cpu_port $Egress_tag
	delete_vlanid $wan_vid $wan_fid
fi
