#!/bin/sh
# Configure SSID parameters
# Needed object: SSID

# Source library script
[ ! "$FAPI_WLAN_WAVE_INIT_PLATFORM" ] && . /tmp/wlan_wave/fapi_wlan_wave_init_platform.sh

print2log DBG "running fapi_wlan_wave_ssid_set: args: $*"

interface_name=$1

# If interface name is not supplied, exit script
check_input_param "fapi_wlan_wave_ssid_set" "interface_name" "$interface_name"

timestamp "fapi_wlan_wave_ssid_set:$interface_name:begin"

# DEBUG: TODO: REMOVE
#cp ${IN_CONF} ${WAVE_TMP}/in_conf_ssid_set

# Map the object index to the received object in the in.conf file
ssid_index=`map_param_index Object $SSID_OBJECT`

# The list of the ssid scripts parameters that we configure on the driver configuration file
ssid_scripts_params="interfaceName
BSSID
ESSID"

# The list of the ssid scripts parameters that we configure on the hostapd configuration file
hostapd_ssid_scripts_params="ESSID"

# Stop the interface by killing hostapd
(. $ETC_PATH/fapi_wlan_wave_init_hostapd.sh stop $interface_name)

# Configure ssid driver parameters
[ -n "$ssid_index" ] && configure_driver_params "$interface_name" "$ssid_index" "$ssid_scripts_params" "${WAVE_TMP}/driver_api_ssid_params_to_set_${interface_name}"

# Configure ssid hostapd parameters
[ -n "$ssid_index" ] && (. $ETC_PATH/fapi_wlan_wave_init_hostapd.sh create_config $interface_name $ssid_index "$hostapd_ssid_scripts_params")

# Create the output configuration file
cat /dev/null > ${OUT_CONF}

# Configuration is completed successfully
update_conf_out "wlan_configuration_status" "success"

# DEBUG: TODO: REMOVE
#cp ${OUT_CONF} ${WAVE_TMP}/out_conf_ssid_set

print2log DBG "fapi_wlan_wave_ssid_set: Done"
timestamp "fapi_wlan_wave_ssid_set:$interface_name:done"
