#!/bin/sh /etc/rc.common

START=04
USE_PROCD=1

validate_system_section()
{
	uci_validate_section system system "${1}" \
		'hostname:string:OpenWrt'
}

hostname_config()
{
	local ipaddr dnsmasq_cmd;
	
	config_load network
	config_get ipaddr lan ipaddr

	# Write in /etc/hosts file. This will be read by dnsmasq.
	if [ -n "$hostname" -a -n "$ipaddr" ]; then
		sed -i '/.*ugwcpe\..*/d' /etc/hosts
		echo "$ipaddr $hostname ugwcpe" >> /etc/hosts
	fi

	# Restart dnsmasq only for explict reload call.
	# Donot restart dnsmasq if call is from hotplug. As lan services SL restarts this anyway.
	if [ -z "$HOTPLUG" -a -f /var/run/dnsmasq.pid ]; then
		dnsmasq_cmd="`strings /proc/$(cat /var/run/dnsmasq.pid)/cmdline`"
		[ -n "$dnsmasq_cmd" ] && {
			kill `cat /var/run/dnsmasq.pid` && $dnsmasq_cmd
		}
	fi
}

system_config() {
	local cfg="$1"

	local hostname

	validate_system_section "${1}" || {
		echo "validation failed"
		return 1
	}

	echo "$hostname" > /proc/sys/kernel/hostname
	hostname_config;
}

reload_service() {
	[ -n "$HOTPLUG" -a "$ipaddr" ] && {
		grep -q "$ipaddr" /etc/hosts && exit 0
	}
	config_load system
	config_foreach system_config system
}

service_triggers()
{
	procd_add_reload_trigger "system"
	procd_add_validation validate_system_section
}

start_service() {
	reload_service
}
