#define DEVICE_WIFI                                                                                                                                           1
#define DEVICE_WIFI_RADIONUMBEROFENTRIES                                                                                                                      2
#define DEVICE_WIFI_SSIDNUMBEROFENTRIES                                                                                                                       3
#define DEVICE_WIFI_ACCESSPOINTNUMBEROFENTRIES                                                                                                                4
#define DEVICE_WIFI_RADIO                                                                                                                                     5
#define DEVICE_WIFI_RADIO_ENABLE                                                                                                                              6
#define DEVICE_WIFI_RADIO_STATUS                                                                                                                              7
#define DEVICE_WIFI_RADIO_ALIAS                                                                                                                               8
#define DEVICE_WIFI_RADIO_NAME                                                                                                                                9
#define DEVICE_WIFI_RADIO_LASTCHANGE                                                                                                                          10
#define DEVICE_WIFI_RADIO_LOWERLAYERS                                                                                                                         11
#define DEVICE_WIFI_RADIO_UPSTREAM                                                                                                                            12
#define DEVICE_WIFI_RADIO_MAXBITRATE                                                                                                                          13
#define DEVICE_WIFI_RADIO_SUPPORTEDFREQUENCYBANDS                                                                                                             14
#define DEVICE_WIFI_RADIO_OPERATINGFREQUENCYBAND                                                                                                              15
#define DEVICE_WIFI_RADIO_SUPPORTEDSTANDARDS                                                                                                                  16
#define DEVICE_WIFI_RADIO_OPERATINGSTANDARDS                                                                                                                  17
#define DEVICE_WIFI_RADIO_POSSIBLECHANNELS                                                                                                                    18
#define DEVICE_WIFI_RADIO_CHANNELSINUSE                                                                                                                       19
#define DEVICE_WIFI_RADIO_CHANNEL                                                                                                                             20
#define DEVICE_WIFI_RADIO_AUTOCHANNELSUPPORTED                                                                                                                21
#define DEVICE_WIFI_RADIO_AUTOCHANNELENABLE                                                                                                                   22
#define DEVICE_WIFI_RADIO_AUTOCHANNELREFRESHPERIOD                                                                                                            23
#define DEVICE_WIFI_RADIO_OPERATINGCHANNELBANDWIDTH                                                                                                           24
#define DEVICE_WIFI_RADIO_EXTENSIONCHANNEL                                                                                                                    25
#define DEVICE_WIFI_RADIO_GUARDINTERVAL                                                                                                                       26
#define DEVICE_WIFI_RADIO_MCS                                                                                                                                 27
#define DEVICE_WIFI_RADIO_TRANSMITPOWERSUPPORTED                                                                                                              28
#define DEVICE_WIFI_RADIO_TRANSMITPOWER                                                                                                                       29
#define DEVICE_WIFI_RADIO_IEEE80211HSUPPORTED                                                                                                                 30
#define DEVICE_WIFI_RADIO_IEEE80211HENABLED                                                                                                                   31
#define DEVICE_WIFI_RADIO_REGULATORYDOMAIN                                                                                                                    32
#define DEVICE_WIFI_RADIO_RETRYLIMIT                                                                                                                          33
#define DEVICE_WIFI_RADIO_CCAREQUEST                                                                                                                          34
#define DEVICE_WIFI_RADIO_CCAREPORT                                                                                                                           35
#define DEVICE_WIFI_RADIO_RPIHISTOGRAMREQUEST                                                                                                                 36
#define DEVICE_WIFI_RADIO_RPIHISTOGRAMREPORT                                                                                                                  37
#define DEVICE_WIFI_RADIO_FRAGMENTATIONTHRESHOLD                                                                                                              38
#define DEVICE_WIFI_RADIO_RTSTHRESHOLD                                                                                                                        39
#define DEVICE_WIFI_RADIO_LONGRETRYLIMIT                                                                                                                      40
#define DEVICE_WIFI_RADIO_BEACONPERIOD                                                                                                                        41
#define DEVICE_WIFI_RADIO_DTIMPERIOD                                                                                                                          42
#define DEVICE_WIFI_RADIO_PACKETAGGREGATIONENABLE                                                                                                             43
#define DEVICE_WIFI_RADIO_PREAMBLETYPE                                                                                                                        44
#define DEVICE_WIFI_RADIO_BASICDATATRANSMITRATES                                                                                                              45
#define DEVICE_WIFI_RADIO_OPERATIONALDATATRANSMITRATES                                                                                                        46
#define DEVICE_WIFI_RADIO_SUPPORTEDDATATRANSMITRATES                                                                                                          47
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR                                                                                                                 48
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_MAXNUMVAPS                                                                                                      49
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_DOT11DENABLE                                                                                                    50
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_DOT11NPROTECTION                                                                                                51
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_TXRETRYLIFETIME                                                                                                 52
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_DYNAMICBANDWIDTHENABLED                                                                                         53
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WAVEEXPLICITBEAMFORMING                                                                                         54
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WAVEIMPLICITBEAMFORMING                                                                                         55
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_AUTOCOCENABLED                                                                                                  56
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WAVEAUTOCOC1X1TIMERINTERVAL                                                                                     57
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WAVEAUTOCOC2X2TIMERINTERVAL                                                                                     58
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WAVEAUTOCOC3X3TIMERINTERVAL                                                                                     59
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WAVEAUTOCOC4X4TIMERINTERVAL                                                                                     60
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WAVEAUTOCOC1X1HIGHLIMIT                                                                                         61
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WAVEAUTOCOC2X2LOWLIMIT                                                                                          62
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WAVEAUTOCOC2X2HIGHLIMIT                                                                                         63
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WAVEAUTOCOC3X3LOWLIMIT                                                                                          64
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WAVEAUTOCOC3X3HIGHLIMIT                                                                                         65
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WAVEAUTOCOC4X4LOWLIMIT                                                                                          66
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_NUMOFANTENNAS                                                                                                   67
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_COEXRSSITHRESHOLD                                                                                               68
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_COEXCHANNELSWITCHTHRESHOLD                                                                                      69
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_COEX40INTOLERANCEENABLED                                                                                        70
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_COEXSCANINTERVAL                                                                                                71
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_COEXPASSIVEDWELL                                                                                                72
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_COEXACTIVEDWELL                                                                                                 73
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_COEXPASSIVEPERCH                                                                                                74
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_COEXACTIVEPERCH                                                                                                 75
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_COEXTRANSDELAY                                                                                                  76
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_COEXACTIVITYTHRESHOLD                                                                                           77
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WAVEPOWERCOCENABLED                                                                                             78
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WAVEDRIVERDEBUGLEVELCONSOLE                                                                                     79
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WAVEFWLOGGERSEVERITY                                                                                            80
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WAVERTLOGGERENABLED                                                                                             81
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WAVEFASTRECOVERYENABLED                                                                                         82
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WAVEFASTRECOVERYLIMIT                                                                                           83
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WAVEFULLRECOVERYENABLED                                                                                         84
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WAVEFULLRECOVERYLIMIT                                                                                           85
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WAVECOMPLETERECOVERYENABLED                                                                                     86
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WAVERECOVERYTIMER                                                                                               87
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WAVEAUTORECOVERYDUMPSENABLED                                                                                    88
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WAVERECOVERYNUMOFDUMPS                                                                                          89
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WAVEFWDEBUGENABLED                                                                                              90
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WAVEDRIVERDEBUGLEVEL                                                                                            91
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WAVECONFIGURATIONDEBUGLEVEL                                                                                     92
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WAVEFWDEBUGLEVEL                                                                                                93
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WAVEHOSTAPDDEBUGLEVEL                                                                                           94
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WAVEHALTONERRORLOG                                                                                              95
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WAVEDRIVERSTREAMNUMBEROFENTRIES                                                                                 96
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WAVECONFIGURATIONSTREAMNUMBEROFENTRIES                                                                          97
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WAVEHOSTAPDSTREAMNUMBEROFENTRIES                                                                                98
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WAVEFWSTREAMNUMBEROFENTRIES                                                                                     99
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WAVEPASSIVESCANTIME                                                                                             100
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WAVEACTIVESCANTIME                                                                                              101
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WAVENUMPROBEREQS                                                                                                102
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WAVEPROBEREQINTERVAL                                                                                            103
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WAVEPASSIVESCANVALIDTIME                                                                                        104
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WAVEACTIVESCANVALIDTIME                                                                                         105
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WAVEPASSIVESCANTIMEBG                                                                                           106
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WAVEACTIVESCANTIMEBG                                                                                            107
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WAVENUMPROBEREQSBG                                                                                              108
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WAVEPROBEREQINTERVALBG                                                                                          109
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WAVENUMCHANSINCHUNKBG                                                                                           110
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WAVECHANCHUNKINTERVALBG                                                                                         111
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WAVESCANMODIFIER                                                                                                112
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WAVECHANNELWIDTHMASK24                                                                                          113
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WAVECHANNELWIDTHMASK5                                                                                           114
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_HTSTBCENABLED                                                                                                   115
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_HTLDPCENABLED                                                                                                   116
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_HTAMSDULEN                                                                                                      117
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_VHTMPDULEN                                                                                                      118
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_VHTLDPCENABLED                                                                                                  119
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_VHTGUARDINTERVAL                                                                                                120
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_VHTSTBCTXENABLED                                                                                                121
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_VHTSTBCRXENABLED                                                                                                122
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_VHTSUBEAMFORMERENABLED                                                                                          123
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_VHTSUBEAMFORMEEENABLED                                                                                          124
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_VHTBFANTENNA                                                                                                    125
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_VHTSOUNDINGDIMENSION                                                                                            126
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_VHTTXOPPOWERSAVEENABLED                                                                                         127
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_VHTAMPDULENEXPONENT                                                                                             128
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WAVEACSNUMSCANS                                                                                                 129
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WAVEACSNUMBSSCOEF                                                                                               130
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WAVERADARSIMULATIONCHANNELENABLED                                                                               131
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WAVERADARSIMULATIONCHANNEL                                                                                      132
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WAVEDOT11HALLOWEDCHANNELS                                                                                       133
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WAVEFASTPATHENABLED                                                                                             134
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WAVEQAMPLUS                                                                                                     135
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WAVEOFFLINECALIBRATIONMASK                                                                                      136
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WAVEONLINECALIBRATIONMASK                                                                                       137
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WAVESCRIPTSDEBUGLEVEL                                                                                           138
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WAVESCRIPTSDEBUGOUTPUT                                                                                          139
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WAVESCRIPTSPROFILINGENABLED                                                                                     140
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WAVEPOWERCOCLIMITLOWER                                                                                          141
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WAVEPOWERCOCLIMITUPPER                                                                                          142
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WAVEPOWERCOCHIGH2LOW                                                                                            143
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WAVEPOWERCOCLOW2HIGH                                                                                            144
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WAVETXOPENABLED                                                                                                 145
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WAVEHTNUMMSDUSINAMSDU                                                                                           146
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WAVEVHTNUMMSDUSINAMSDU                                                                                          147
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_NUMOFANTENNASSUPPORTED                                                                                          148
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WAVEASSOCRESPRXMCSMASK                                                                                          149
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WAVESCANEXPIRATIONTIME                                                                                          150
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_COEXENABLED                                                                                                     151
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WAVEIGNORE40MHZINTOLERANT                                                                                       152
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WAVERADARDETECTRSSITHRESHOLD                                                                                    153
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WAVEDRIVERSTREAM                                                                                                154
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WAVEDRIVERSTREAM_WAVEDRIVERSTREAMNUMBER                                                                         155
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WAVEDRIVERSTREAM_WAVEDRIVERSTREAMENABLE                                                                         156
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WAVEDRIVERSTREAM_WAVEDRIVERREMOTEINTERFACE                                                                      157
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WAVEDRIVERSTREAM_WAVEDRIVERDESTINATIONIP                                                                        158
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WAVEDRIVERSTREAM_WAVEDRIVERDESTINATIONMACADDRESS                                                                159
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WAVECONFIGURATIONSTREAM                                                                                         160
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WAVECONFIGURATIONSTREAM_WAVECONFIGURATIONSTREAMNUMBER                                                           161
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WAVECONFIGURATIONSTREAM_WAVECONFIGURATIONSTREAMENABLE                                                           162
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WAVECONFIGURATIONSTREAM_WAVECONFIGURATIONREMOTEINTERFACE                                                        163
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WAVECONFIGURATIONSTREAM_WAVECONFIGURATIONDESTINATIONIP                                                          164
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WAVECONFIGURATIONSTREAM_WAVECONFIGURATIONDESTINATIONMACADDRESS                                                  165
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WAVEHOSTAPDSTREAM                                                                                               166
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WAVEHOSTAPDSTREAM_WAVEHOSTAPDSTREAMNUMBER                                                                       167
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WAVEHOSTAPDSTREAM_WAVEHOSTAPDSTREAMENABLE                                                                       168
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WAVEHOSTAPDSTREAM_WAVEHOSTAPDREMOTEINTERFACE                                                                    169
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WAVEHOSTAPDSTREAM_WAVEHOSTAPDDESTINATIONIP                                                                      170
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WAVEHOSTAPDSTREAM_WAVEHOSTAPDDESTINATIONMACADDRESS                                                              171
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WAVEFWSTREAM                                                                                                    172
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WAVEFWSTREAM_WAVEFWSTREAMNUMBER                                                                                 173
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WAVEFWSTREAM_WAVEFWSTREAMENABLE                                                                                 174
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WAVEFWSTREAM_WAVEFWREMOTEINTERFACE                                                                              175
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WAVEFWSTREAM_WAVEFWDESTINATIONIP                                                                                176
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WAVEFWSTREAM_WAVEFWDESTINATIONMACADDRESS                                                                        177
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WAVEFWSTREAM_WAVEMACFIFO                                                                                        178
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WAVEFWSTREAM_WAVEHOSTIFFIFO                                                                                     179
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WAVEFWSTREAM_WAVERXHANDLERRISCFIFO                                                                              180
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WAVEFWSTREAM_WAVEPHYGENRISCFIFO                                                                                 181
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WAVEFWSTREAM_WAVEPHYHW                                                                                          182
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WAVEFWSTREAM_WAVEHWFIFO1                                                                                        183
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WAVEFWSTREAM_WAVEHWFIFO2                                                                                        184
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WAVEFWSTREAM_WAVEHWFIFO3                                                                                        185
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WAVEFWSTREAM_WAVEHWFIFO4                                                                                        186
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WAVEFWSTREAM_WAVEHWFIFO5                                                                                        187
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WAVEFWSTREAM_WAVEHWFIFO6                                                                                        188
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WAVEFWSTREAM_WAVEHWFIFO1MODULE                                                                                  189
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WAVEFWSTREAM_WAVEHWFIFO2MODULE                                                                                  190
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WAVEFWSTREAM_WAVEHWFIFO3MODULE                                                                                  191
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WAVEFWSTREAM_WAVEHWFIFO4MODULE                                                                                  192
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WAVEFWSTREAM_WAVEHWFIFO5MODULE                                                                                  193
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WAVEFWSTREAM_WAVEHWFIFO6MODULE                                                                                  194
#define DEVICE_WIFI_RADIO_STATS                                                                                                                               195
#define DEVICE_WIFI_RADIO_STATS_BYTESSENT                                                                                                                     196
#define DEVICE_WIFI_RADIO_STATS_BYTESRECEIVED                                                                                                                 197
#define DEVICE_WIFI_RADIO_STATS_PACKETSSENT                                                                                                                   198
#define DEVICE_WIFI_RADIO_STATS_PACKETSRECEIVED                                                                                                               199
#define DEVICE_WIFI_RADIO_STATS_ERRORSSENT                                                                                                                    200
#define DEVICE_WIFI_RADIO_STATS_ERRORSRECEIVED                                                                                                                201
#define DEVICE_WIFI_RADIO_STATS_DISCARDPACKETSSENT                                                                                                            202
#define DEVICE_WIFI_RADIO_STATS_DISCARDPACKETSRECEIVED                                                                                                        203
#define DEVICE_WIFI_RADIO_STATS_PLCPERRORCOUNT                                                                                                                204
#define DEVICE_WIFI_RADIO_STATS_FCSERRORCOUNT                                                                                                                 205
#define DEVICE_WIFI_RADIO_STATS_INVALIDMACCOUNT                                                                                                               206
#define DEVICE_WIFI_RADIO_STATS_PACKETSOTHERRECEIVED                                                                                                          207
#define DEVICE_WIFI_RADIO_STATS_NOISE                                                                                                                         208
#define DEVICE_WIFI_NEIGHBORINGWIFIDIAGNOSTIC                                                                                                                 209
#define DEVICE_WIFI_NEIGHBORINGWIFIDIAGNOSTIC_DIAGNOSTICSSTATE                                                                                                210
#define DEVICE_WIFI_NEIGHBORINGWIFIDIAGNOSTIC_RESULTNUMBEROFENTRIES                                                                                           211
#define DEVICE_WIFI_NEIGHBORINGWIFIDIAGNOSTIC_RESULT                                                                                                          212
#define DEVICE_WIFI_NEIGHBORINGWIFIDIAGNOSTIC_RESULT_RADIO                                                                                                    213
#define DEVICE_WIFI_NEIGHBORINGWIFIDIAGNOSTIC_RESULT_SSID                                                                                                     214
#define DEVICE_WIFI_NEIGHBORINGWIFIDIAGNOSTIC_RESULT_BSSID                                                                                                    215
#define DEVICE_WIFI_NEIGHBORINGWIFIDIAGNOSTIC_RESULT_MODE                                                                                                     216
#define DEVICE_WIFI_NEIGHBORINGWIFIDIAGNOSTIC_RESULT_CHANNEL                                                                                                  217
#define DEVICE_WIFI_NEIGHBORINGWIFIDIAGNOSTIC_RESULT_SIGNALSTRENGTH                                                                                           218
#define DEVICE_WIFI_NEIGHBORINGWIFIDIAGNOSTIC_RESULT_SECURITYMODEENABLED                                                                                      219
#define DEVICE_WIFI_NEIGHBORINGWIFIDIAGNOSTIC_RESULT_ENCRYPTIONMODE                                                                                           220
#define DEVICE_WIFI_NEIGHBORINGWIFIDIAGNOSTIC_RESULT_OPERATINGFREQUENCYBAND                                                                                   221
#define DEVICE_WIFI_NEIGHBORINGWIFIDIAGNOSTIC_RESULT_SUPPORTEDSTANDARDS                                                                                       222
#define DEVICE_WIFI_NEIGHBORINGWIFIDIAGNOSTIC_RESULT_OPERATINGSTANDARDS                                                                                       223
#define DEVICE_WIFI_NEIGHBORINGWIFIDIAGNOSTIC_RESULT_OPERATINGCHANNELBANDWIDTH                                                                                224
#define DEVICE_WIFI_NEIGHBORINGWIFIDIAGNOSTIC_RESULT_BEACONPERIOD                                                                                             225
#define DEVICE_WIFI_NEIGHBORINGWIFIDIAGNOSTIC_RESULT_NOISE                                                                                                    226
#define DEVICE_WIFI_NEIGHBORINGWIFIDIAGNOSTIC_RESULT_BASICDATATRANSFERRATES                                                                                   227
#define DEVICE_WIFI_NEIGHBORINGWIFIDIAGNOSTIC_RESULT_SUPPORTEDDATATRANSFERRATES                                                                               228
#define DEVICE_WIFI_NEIGHBORINGWIFIDIAGNOSTIC_RESULT_DTIMPERIOD                                                                                               229
#define DEVICE_WIFI_SSID                                                                                                                                      230
#define DEVICE_WIFI_SSID_ENABLE                                                                                                                               231
#define DEVICE_WIFI_SSID_STATUS                                                                                                                               232
#define DEVICE_WIFI_SSID_ALIAS                                                                                                                                233
#define DEVICE_WIFI_SSID_NAME                                                                                                                                 234
#define DEVICE_WIFI_SSID_LASTCHANGE                                                                                                                           235
#define DEVICE_WIFI_SSID_LOWERLAYERS                                                                                                                          236
#define DEVICE_WIFI_SSID_BSSID                                                                                                                                237
#define DEVICE_WIFI_SSID_MACADDRESS                                                                                                                           238
#define DEVICE_WIFI_SSID_SSID                                                                                                                                 239
#define DEVICE_WIFI_SSID_STATS                                                                                                                                240
#define DEVICE_WIFI_SSID_STATS_BYTESSENT                                                                                                                      241
#define DEVICE_WIFI_SSID_STATS_BYTESRECEIVED                                                                                                                  242
#define DEVICE_WIFI_SSID_STATS_PACKETSSENT                                                                                                                    243
#define DEVICE_WIFI_SSID_STATS_PACKETSRECEIVED                                                                                                                244
#define DEVICE_WIFI_SSID_STATS_ERRORSSENT                                                                                                                     245
#define DEVICE_WIFI_SSID_STATS_RETRANSCOUNT                                                                                                                   246
#define DEVICE_WIFI_SSID_STATS_FAILEDRETRANSCOUNT                                                                                                             247
#define DEVICE_WIFI_SSID_STATS_RETRYCOUNT                                                                                                                     248
#define DEVICE_WIFI_SSID_STATS_MULTIPLERETRYCOUNT                                                                                                             249
#define DEVICE_WIFI_SSID_STATS_ACKFAILURECOUNT                                                                                                                250
#define DEVICE_WIFI_SSID_STATS_AGGREGATEDPACKETCOUNT                                                                                                          251
#define DEVICE_WIFI_SSID_STATS_ERRORSRECEIVED                                                                                                                 252
#define DEVICE_WIFI_SSID_STATS_UNICASTPACKETSSENT                                                                                                             253
#define DEVICE_WIFI_SSID_STATS_UNICASTPACKETSRECEIVED                                                                                                         254
#define DEVICE_WIFI_SSID_STATS_DISCARDPACKETSSENT                                                                                                             255
#define DEVICE_WIFI_SSID_STATS_DISCARDPACKETSRECEIVED                                                                                                         256
#define DEVICE_WIFI_SSID_STATS_MULTICASTPACKETSSENT                                                                                                           257
#define DEVICE_WIFI_SSID_STATS_MULTICASTPACKETSRECEIVED                                                                                                       258
#define DEVICE_WIFI_SSID_STATS_BROADCASTPACKETSSENT                                                                                                           259
#define DEVICE_WIFI_SSID_STATS_BROADCASTPACKETSRECEIVED                                                                                                       260
#define DEVICE_WIFI_SSID_STATS_UNKNOWNPROTOPACKETSRECEIVED                                                                                                    261
#define DEVICE_WIFI_ACCESSPOINT                                                                                                                               262
#define DEVICE_WIFI_ACCESSPOINT_ENABLE                                                                                                                        263
#define DEVICE_WIFI_ACCESSPOINT_STATUS                                                                                                                        264
#define DEVICE_WIFI_ACCESSPOINT_ALIAS                                                                                                                         265
#define DEVICE_WIFI_ACCESSPOINT_SSIDREFERENCE                                                                                                                 266
#define DEVICE_WIFI_ACCESSPOINT_SSIDADVERTISEMENTENABLED                                                                                                      267
#define DEVICE_WIFI_ACCESSPOINT_WMMCAPABILITY                                                                                                                 268
#define DEVICE_WIFI_ACCESSPOINT_UAPSDCAPABILITY                                                                                                               269
#define DEVICE_WIFI_ACCESSPOINT_WMMENABLE                                                                                                                     270
#define DEVICE_WIFI_ACCESSPOINT_UAPSDENABLE                                                                                                                   271
#define DEVICE_WIFI_ACCESSPOINT_ASSOCIATEDDEVICENUMBEROFENTRIES                                                                                               272
#define DEVICE_WIFI_ACCESSPOINT_MAXASSOCIATEDDEVICES                                                                                                          273
#define DEVICE_WIFI_ACCESSPOINT_ISOLATIONENABLE                                                                                                               274
#define DEVICE_WIFI_ACCESSPOINT_SECURITY                                                                                                                      275
#define DEVICE_WIFI_ACCESSPOINT_SECURITY_RESET                                                                                                                276
#define DEVICE_WIFI_ACCESSPOINT_SECURITY_MODESSUPPORTED                                                                                                       277
#define DEVICE_WIFI_ACCESSPOINT_SECURITY_MODEENABLED                                                                                                          278
#define DEVICE_WIFI_ACCESSPOINT_SECURITY_WEPKEY                                                                                                               279
#define DEVICE_WIFI_ACCESSPOINT_SECURITY_PRESHAREDKEY                                                                                                         280
#define DEVICE_WIFI_ACCESSPOINT_SECURITY_KEYPASSPHRASE                                                                                                        281
#define DEVICE_WIFI_ACCESSPOINT_SECURITY_REKEYINGINTERVAL                                                                                                     282
#define DEVICE_WIFI_ACCESSPOINT_SECURITY_RADIUSSERVERIPADDR                                                                                                   283
#define DEVICE_WIFI_ACCESSPOINT_SECURITY_SECONDARYRADIUSSERVERIPADDR                                                                                          284
#define DEVICE_WIFI_ACCESSPOINT_SECURITY_RADIUSSERVERPORT                                                                                                     285
#define DEVICE_WIFI_ACCESSPOINT_SECURITY_SECONDARYRADIUSSERVERPORT                                                                                            286
#define DEVICE_WIFI_ACCESSPOINT_SECURITY_RADIUSSECRET                                                                                                         287
#define DEVICE_WIFI_ACCESSPOINT_SECURITY_SECONDARYRADIUSSECRET                                                                                                288
#define DEVICE_WIFI_ACCESSPOINT_WPS                                                                                                                           289
#define DEVICE_WIFI_ACCESSPOINT_WPS_ENABLE                                                                                                                    290
#define DEVICE_WIFI_ACCESSPOINT_WPS_CONFIGMETHODSSUPPORTED                                                                                                    291
#define DEVICE_WIFI_ACCESSPOINT_WPS_CONFIGMETHODSENABLED                                                                                                      292
#define DEVICE_WIFI_ACCESSPOINT_ASSOCIATEDDEVICE                                                                                                              293
#define DEVICE_WIFI_ACCESSPOINT_ASSOCIATEDDEVICE_MACADDRESS                                                                                                   294
#define DEVICE_WIFI_ACCESSPOINT_ASSOCIATEDDEVICE_AUTHENTICATIONSTATE                                                                                          295
#define DEVICE_WIFI_ACCESSPOINT_ASSOCIATEDDEVICE_LASTDATADOWNLINKRATE                                                                                         296
#define DEVICE_WIFI_ACCESSPOINT_ASSOCIATEDDEVICE_LASTDATAUPLINKRATE                                                                                           297
#define DEVICE_WIFI_ACCESSPOINT_ASSOCIATEDDEVICE_SIGNALSTRENGTH                                                                                               298
#define DEVICE_WIFI_ACCESSPOINT_ASSOCIATEDDEVICE_RETRANSMISSIONS                                                                                              299
#define DEVICE_WIFI_ACCESSPOINT_ASSOCIATEDDEVICE_ACTIVE                                                                                                       300
#define DEVICE_WIFI_ACCESSPOINT_ASSOCIATEDDEVICE_X_LANTIQ_COM_VENDOR_SIGNALSTRENGTH2                                                                          301
#define DEVICE_WIFI_ACCESSPOINT_ASSOCIATEDDEVICE_X_LANTIQ_COM_VENDOR_SIGNALSTRENGTH3                                                                          302
#define DEVICE_WIFI_ACCESSPOINT_ASSOCIATEDDEVICE_X_LANTIQ_COM_VENDOR_SIGNALSTRENGTH4                                                                          303
#define DEVICE_WIFI_ACCESSPOINT_ASSOCIATEDDEVICE_X_LANTIQ_COM_VENDOR                                                                                          304
#define DEVICE_WIFI_ACCESSPOINT_ASSOCIATEDDEVICE_X_LANTIQ_COM_VENDOR_IPADDRESS                                                                                305
#define DEVICE_WIFI_ACCESSPOINT_ASSOCIATEDDEVICE_X_LANTIQ_COM_VENDOR_SECURITYMODE                                                                             306
#define DEVICE_WIFI_ACCESSPOINT_ASSOCIATEDDEVICE_STATS                                                                                                        307
#define DEVICE_WIFI_ACCESSPOINT_ASSOCIATEDDEVICE_STATS_BYTESSENT                                                                                              308
#define DEVICE_WIFI_ACCESSPOINT_ASSOCIATEDDEVICE_STATS_BYTESRECEIVED                                                                                          309
#define DEVICE_WIFI_ACCESSPOINT_ASSOCIATEDDEVICE_STATS_PACKETSSENT                                                                                            310
#define DEVICE_WIFI_ACCESSPOINT_ASSOCIATEDDEVICE_STATS_PACKETSRECEIVED                                                                                        311
#define DEVICE_WIFI_ACCESSPOINT_ASSOCIATEDDEVICE_STATS_ERRORSSENT                                                                                             312
#define DEVICE_WIFI_ACCESSPOINT_ASSOCIATEDDEVICE_STATS_RETRANSCOUNT                                                                                           313
#define DEVICE_WIFI_ACCESSPOINT_ASSOCIATEDDEVICE_STATS_FAILEDRETRANSCOUNT                                                                                     314
#define DEVICE_WIFI_ACCESSPOINT_ASSOCIATEDDEVICE_STATS_RETRYCOUNT                                                                                             315
#define DEVICE_WIFI_ACCESSPOINT_ASSOCIATEDDEVICE_STATS_MULTIPLERETRYCOUNT                                                                                     316
#define DEVICE_WIFI_ACCESSPOINT_AC                                                                                                                            317
#define DEVICE_WIFI_ACCESSPOINT_AC_ACCESSCATEGORY                                                                                                             318
#define DEVICE_WIFI_ACCESSPOINT_AC_ALIAS                                                                                                                      319
#define DEVICE_WIFI_ACCESSPOINT_AC_AIFSN                                                                                                                      320
#define DEVICE_WIFI_ACCESSPOINT_AC_ECWMIN                                                                                                                     321
#define DEVICE_WIFI_ACCESSPOINT_AC_ECWMAX                                                                                                                     322
#define DEVICE_WIFI_ACCESSPOINT_AC_TXOPMAX                                                                                                                    323
#define DEVICE_WIFI_ACCESSPOINT_AC_ACKPOLICY                                                                                                                  324
#define DEVICE_WIFI_ACCESSPOINT_AC_OUTQLENHISTOGRAMINTERVALS                                                                                                  325
#define DEVICE_WIFI_ACCESSPOINT_AC_OUTQLENHISTOGRAMSAMPLEINTERVAL                                                                                             326
#define DEVICE_WIFI_ACCESSPOINT_AC_STATS                                                                                                                      327
#define DEVICE_WIFI_ACCESSPOINT_AC_STATS_BYTESSENT                                                                                                            328
#define DEVICE_WIFI_ACCESSPOINT_AC_STATS_BYTESRECEIVED                                                                                                        329
#define DEVICE_WIFI_ACCESSPOINT_AC_STATS_PACKETSSENT                                                                                                          330
#define DEVICE_WIFI_ACCESSPOINT_AC_STATS_PACKETSRECEIVED                                                                                                      331
#define DEVICE_WIFI_ACCESSPOINT_AC_STATS_ERRORSSENT                                                                                                           332
#define DEVICE_WIFI_ACCESSPOINT_AC_STATS_ERRORSRECEIVED                                                                                                       333
#define DEVICE_WIFI_ACCESSPOINT_AC_STATS_DISCARDPACKETSSENT                                                                                                   334
#define DEVICE_WIFI_ACCESSPOINT_AC_STATS_DISCARDPACKETSRECEIVED                                                                                               335
#define DEVICE_WIFI_ACCESSPOINT_AC_STATS_RETRANSCOUNT                                                                                                         336
#define DEVICE_WIFI_ACCESSPOINT_AC_STATS_OUTQLENHISTOGRAM                                                                                                     337
#define DEVICE_WIFI_ACCESSPOINT_X_LANTIQ_COM_VENDOR                                                                                                           338
#define DEVICE_WIFI_ACCESSPOINT_X_LANTIQ_COM_VENDOR_MACADDRESSCONTROLENABLED                                                                                  339
#define DEVICE_WIFI_ACCESSPOINT_X_LANTIQ_COM_VENDOR_ALLOWEDMACADDRESS                                                                                         340
#define DEVICE_WIFI_ACCESSPOINT_X_LANTIQ_COM_VENDOR_MACADDRESSCONTROLMODE                                                                                     341
#define DEVICE_WIFI_ACCESSPOINT_X_LANTIQ_COM_VENDOR_MACADDRESSCONTROLLIST                                                                                     342
#define DEVICE_WIFI_ACCESSPOINT_X_LANTIQ_COM_VENDOR_RESERVEDASSOCIATEDDEVICES                                                                                 343
#define DEVICE_WIFI_ACCESSPOINT_X_LANTIQ_COM_VENDOR_RELIABLEMUTICASTENABLE                                                                                    344
#define DEVICE_WIFI_ACCESSPOINT_X_LANTIQ_COM_VENDOR_PPAENABLE                                                                                                 345
#define DEVICE_WIFI_ACCESSPOINT_X_LANTIQ_COM_VENDOR_APMAXINACTIVITY                                                                                           346
#define DEVICE_WIFI_ACCESSPOINT_X_LANTIQ_COM_VENDOR_WAVEWDSENABLED                                                                                            347
#define DEVICE_WIFI_ACCESSPOINT_X_LANTIQ_COM_VENDOR_WAVEWDSSECURITYMODE                                                                                       348
#define DEVICE_WIFI_ACCESSPOINT_X_LANTIQ_COM_VENDOR_WAVEWDSKEY                                                                                                349
#define DEVICE_WIFI_ACCESSPOINT_X_LANTIQ_COM_VENDOR_WAVEWDSPEERS                                                                                              350
#define DEVICE_WIFI_ACCESSPOINT_X_LANTIQ_COM_VENDOR_QOSMAP                                                                                                    351
#define DEVICE_WIFI_ACCESSPOINT_X_LANTIQ_COM_VENDOR_SENDQOSMAPFRAME                                                                                           352
#define DEVICE_WIFI_ACCESSPOINT_X_LANTIQ_COM_VENDOR_PROXYARP                                                                                                  353
#define DEVICE_WIFI_ACCESSPOINT_X_LANTIQ_COM_VENDOR_WAVEAMSDUENABLED                                                                                          354
#define DEVICE_WIFI_ACCESSPOINT_X_LANTIQ_COM_VENDOR_SECURITY                                                                                                  355
#define DEVICE_WIFI_ACCESSPOINT_X_LANTIQ_COM_VENDOR_SECURITY_MANAGEMENTFRAMEPROTECTION                                                                        356
#define DEVICE_WIFI_ACCESSPOINT_X_LANTIQ_COM_VENDOR_SECURITY_SAQUERYMAXTIMEOUT                                                                                357
#define DEVICE_WIFI_ACCESSPOINT_X_LANTIQ_COM_VENDOR_SECURITY_SAQUERYRETRYTIMEOUT                                                                              358
#define DEVICE_WIFI_ACCESSPOINT_X_LANTIQ_COM_VENDOR_WPS                                                                                                       359
#define DEVICE_WIFI_ACCESSPOINT_X_LANTIQ_COM_VENDOR_WPS_STATUS                                                                                                360
#define DEVICE_WIFI_ACCESSPOINT_X_LANTIQ_COM_VENDOR_WPS_WPS2CONFIGMETHODSSUPPORTED                                                                            361
#define DEVICE_WIFI_ACCESSPOINT_X_LANTIQ_COM_VENDOR_WPS_WPS2CONFIGMETHODSENABLED                                                                              362
#define DEVICE_WIFI_ACCESSPOINT_X_LANTIQ_COM_VENDOR_WPS_PIN                                                                                                   363
#define DEVICE_WIFI_ACCESSPOINT_X_LANTIQ_COM_VENDOR_WPS_CONFIGSTATE                                                                                           364
#define DEVICE_WIFI_ACCESSPOINT_X_LANTIQ_COM_VENDOR_WPS_AUTHORIZEDMAC                                                                                         365
#define DEVICE_WIFI_ACCESSPOINT_X_LANTIQ_COM_VENDOR_WPS_ENDPOINTPIN                                                                                           366
#define DEVICE_WIFI_ACCESSPOINT_X_LANTIQ_COM_VENDOR_WPS_WPSACTION                                                                                             367
#define DEVICE_WIFI_ACCESSPOINT_X_LANTIQ_COM_VENDOR_WPS_UUID                                                                                                  368
#define DEVICE_WIFI_ACCESSPOINT_X_LANTIQ_COM_VENDOR_WPS_DEVICENAME                                                                                            369
#define DEVICE_WIFI_ACCESSPOINT_X_LANTIQ_COM_VENDOR_WPS_MANUFACTURERURL                                                                                       370
#define DEVICE_WIFI_ACCESSPOINT_X_LANTIQ_COM_VENDOR_AC                                                                                                        371
#define DEVICE_WIFI_ACCESSPOINT_X_LANTIQ_COM_VENDOR_AC_ACCESSCATEGORY                                                                                         372
#define DEVICE_WIFI_ACCESSPOINT_X_LANTIQ_COM_VENDOR_AC_WAVESTAAIFSN                                                                                           373
#define DEVICE_WIFI_ACCESSPOINT_X_LANTIQ_COM_VENDOR_AC_WAVESTAECWMIN                                                                                          374
#define DEVICE_WIFI_ACCESSPOINT_X_LANTIQ_COM_VENDOR_AC_WAVESTAECWMAX                                                                                          375
#define DEVICE_WIFI_ACCESSPOINT_X_LANTIQ_COM_VENDOR_AC_WAVESTATXOPMAX                                                                                         376
#define DEVICE_WIFI_ACCESSPOINT_X_LANTIQ_COM_VENDOR_HS20                                                                                                      377
#define DEVICE_WIFI_ACCESSPOINT_X_LANTIQ_COM_VENDOR_HS20_ENABLE                                                                                               378
#define DEVICE_WIFI_ACCESSPOINT_X_LANTIQ_COM_VENDOR_HS20_OSENENABLED                                                                                          379
#define DEVICE_WIFI_ACCESSPOINT_X_LANTIQ_COM_VENDOR_HS20_DGAFDISABLED                                                                                         380
#define DEVICE_WIFI_ACCESSPOINT_X_LANTIQ_COM_VENDOR_HS20_ANQPDOMAINID                                                                                         381
#define DEVICE_WIFI_ACCESSPOINT_X_LANTIQ_COM_VENDOR_HS20_ACCESSNETWORKTYPE                                                                                    382
#define DEVICE_WIFI_ACCESSPOINT_X_LANTIQ_COM_VENDOR_HS20_NETWORKAUTHENTICATIONTYPE                                                                            383
#define DEVICE_WIFI_ACCESSPOINT_X_LANTIQ_COM_VENDOR_HS20_NETWORKAUTHENTICATIONURL                                                                             384
#define DEVICE_WIFI_ACCESSPOINT_X_LANTIQ_COM_VENDOR_HS20_INTERNETCONNECTIVITYENABLED                                                                          385
#define DEVICE_WIFI_ACCESSPOINT_X_LANTIQ_COM_VENDOR_HS20_DOMAINNAME                                                                                           386
#define DEVICE_WIFI_ACCESSPOINT_X_LANTIQ_COM_VENDOR_HS20_HESSID                                                                                               387
#define DEVICE_WIFI_ACCESSPOINT_X_LANTIQ_COM_VENDOR_HS20_IPV4ADDRESSTYPE                                                                                      388
#define DEVICE_WIFI_ACCESSPOINT_X_LANTIQ_COM_VENDOR_HS20_IPV6ADDRESSTYPE                                                                                      389
#define DEVICE_WIFI_ACCESSPOINT_X_LANTIQ_COM_VENDOR_HS20_THREEGPP                                                                                             390
#define DEVICE_WIFI_ACCESSPOINT_X_LANTIQ_COM_VENDOR_HS20_GASCOMEBACKDELAY                                                                                     391
#define DEVICE_WIFI_ACCESSPOINT_X_LANTIQ_COM_VENDOR_HS20_OPERATINGCLASS                                                                                       392
#define DEVICE_WIFI_ACCESSPOINT_X_LANTIQ_COM_VENDOR_HS20_VENUEGROUP                                                                                           393
#define DEVICE_WIFI_ACCESSPOINT_X_LANTIQ_COM_VENDOR_HS20_VENUETYPE                                                                                            394
#define DEVICE_WIFI_ACCESSPOINT_X_LANTIQ_COM_VENDOR_HS20_OSUSSID                                                                                              395
#define DEVICE_WIFI_ACCESSPOINT_X_LANTIQ_COM_VENDOR_HS20_L2FWENABLED                                                                                          396
#define DEVICE_WIFI_ACCESSPOINT_X_LANTIQ_COM_VENDOR_HS20_WANMETRICSDURATION                                                                                   397
#define DEVICE_WIFI_ACCESSPOINT_X_LANTIQ_COM_VENDOR_HS20_WANPORT                                                                                              398
#define DEVICE_WIFI_ACCESSPOINT_X_LANTIQ_COM_VENDOR_HS20_OPERATORFRIENDLYNAMENUMBEROFENTRIES                                                                  399
#define DEVICE_WIFI_ACCESSPOINT_X_LANTIQ_COM_VENDOR_HS20_VENUENAMENUMBEROFENTRIES                                                                             400
#define DEVICE_WIFI_ACCESSPOINT_X_LANTIQ_COM_VENDOR_HS20_ROAMINGCONSORTIUMNUMBEROFENTRIES                                                                     401
#define DEVICE_WIFI_ACCESSPOINT_X_LANTIQ_COM_VENDOR_HS20_CONNECTIONCAPABILITYNUMBEROFENTRIES                                                                  402
#define DEVICE_WIFI_ACCESSPOINT_X_LANTIQ_COM_VENDOR_HS20_NAIREALMNUMBEROFENTRIES                                                                              403
#define DEVICE_WIFI_ACCESSPOINT_X_LANTIQ_COM_VENDOR_HS20_WANMETRICSNUMBEROFENTRIES                                                                            404
#define DEVICE_WIFI_ACCESSPOINT_X_LANTIQ_COM_VENDOR_HS20_OSUICONSNUMBEROFENTRIES                                                                              405
#define DEVICE_WIFI_ACCESSPOINT_X_LANTIQ_COM_VENDOR_HS20_OSUPROVIDERSNUMBEROFENTRIES                                                                          406
#define DEVICE_WIFI_ACCESSPOINT_X_LANTIQ_COM_VENDOR_HS20_L2FIREWALLNUMBEROFENTRIES                                                                            407
#define DEVICE_WIFI_ACCESSPOINT_X_LANTIQ_COM_VENDOR_HS20_OPERATORFRIENDLYNAME                                                                                 408
#define DEVICE_WIFI_ACCESSPOINT_X_LANTIQ_COM_VENDOR_HS20_OPERATORFRIENDLYNAME_OPERATORFRIENDLYNAME                                                            409
#define DEVICE_WIFI_ACCESSPOINT_X_LANTIQ_COM_VENDOR_HS20_VENUENAME                                                                                            410
#define DEVICE_WIFI_ACCESSPOINT_X_LANTIQ_COM_VENDOR_HS20_VENUENAME_VENUENAME                                                                                  411
#define DEVICE_WIFI_ACCESSPOINT_X_LANTIQ_COM_VENDOR_HS20_ROAMINGCONSORTIUM                                                                                    412
#define DEVICE_WIFI_ACCESSPOINT_X_LANTIQ_COM_VENDOR_HS20_ROAMINGCONSORTIUM_ROAMINGCONSORTIUM                                                                  413
#define DEVICE_WIFI_ACCESSPOINT_X_LANTIQ_COM_VENDOR_HS20_CONNECTIONCAPABILITY                                                                                 414
#define DEVICE_WIFI_ACCESSPOINT_X_LANTIQ_COM_VENDOR_HS20_CONNECTIONCAPABILITY_PROTOCOL                                                                        415
#define DEVICE_WIFI_ACCESSPOINT_X_LANTIQ_COM_VENDOR_HS20_CONNECTIONCAPABILITY_PORT                                                                            416
#define DEVICE_WIFI_ACCESSPOINT_X_LANTIQ_COM_VENDOR_HS20_CONNECTIONCAPABILITY_STATUS                                                                          417
#define DEVICE_WIFI_ACCESSPOINT_X_LANTIQ_COM_VENDOR_HS20_NAIREALM                                                                                             418
#define DEVICE_WIFI_ACCESSPOINT_X_LANTIQ_COM_VENDOR_HS20_NAIREALM_NAIREALMNAME                                                                                419
#define DEVICE_WIFI_ACCESSPOINT_X_LANTIQ_COM_VENDOR_HS20_NAIREALM_EAPMETHOD1                                                                                  420
#define DEVICE_WIFI_ACCESSPOINT_X_LANTIQ_COM_VENDOR_HS20_NAIREALM_EAPMETHOD2                                                                                  421
#define DEVICE_WIFI_ACCESSPOINT_X_LANTIQ_COM_VENDOR_HS20_WANMETRICS                                                                                           422
#define DEVICE_WIFI_ACCESSPOINT_X_LANTIQ_COM_VENDOR_HS20_WANMETRICS_LINKSTATUS                                                                                423
#define DEVICE_WIFI_ACCESSPOINT_X_LANTIQ_COM_VENDOR_HS20_WANMETRICS_SYMMETRICLINK                                                                             424
#define DEVICE_WIFI_ACCESSPOINT_X_LANTIQ_COM_VENDOR_HS20_WANMETRICS_ATCAPACITY                                                                                425
#define DEVICE_WIFI_ACCESSPOINT_X_LANTIQ_COM_VENDOR_HS20_WANMETRICS_DLSPEED                                                                                   426
#define DEVICE_WIFI_ACCESSPOINT_X_LANTIQ_COM_VENDOR_HS20_WANMETRICS_ULSPEED                                                                                   427
#define DEVICE_WIFI_ACCESSPOINT_X_LANTIQ_COM_VENDOR_HS20_WANMETRICS_DLLOAD                                                                                    428
#define DEVICE_WIFI_ACCESSPOINT_X_LANTIQ_COM_VENDOR_HS20_WANMETRICS_ULLOAD                                                                                    429
#define DEVICE_WIFI_ACCESSPOINT_X_LANTIQ_COM_VENDOR_HS20_WANMETRICS_LOADMEASUREMENTDURATION                                                                   430
#define DEVICE_WIFI_ACCESSPOINT_X_LANTIQ_COM_VENDOR_HS20_OSUICONS                                                                                             431
#define DEVICE_WIFI_ACCESSPOINT_X_LANTIQ_COM_VENDOR_HS20_OSUICONS_WIDTH                                                                                       432
#define DEVICE_WIFI_ACCESSPOINT_X_LANTIQ_COM_VENDOR_HS20_OSUICONS_HEIGHT                                                                                      433
#define DEVICE_WIFI_ACCESSPOINT_X_LANTIQ_COM_VENDOR_HS20_OSUICONS_LANGUAGECODE                                                                                434
#define DEVICE_WIFI_ACCESSPOINT_X_LANTIQ_COM_VENDOR_HS20_OSUICONS_TYPE                                                                                        435
#define DEVICE_WIFI_ACCESSPOINT_X_LANTIQ_COM_VENDOR_HS20_OSUICONS_NAME                                                                                        436
#define DEVICE_WIFI_ACCESSPOINT_X_LANTIQ_COM_VENDOR_HS20_OSUICONS_FILEPATH                                                                                    437
#define DEVICE_WIFI_ACCESSPOINT_X_LANTIQ_COM_VENDOR_HS20_OSUPROVIDERS                                                                                         438
#define DEVICE_WIFI_ACCESSPOINT_X_LANTIQ_COM_VENDOR_HS20_OSUPROVIDERS_OSUPROVIDERSERVERURI                                                                    439
#define DEVICE_WIFI_ACCESSPOINT_X_LANTIQ_COM_VENDOR_HS20_OSUPROVIDERS_OSUPROVIDERFRIENDLYNAME                                                                 440
#define DEVICE_WIFI_ACCESSPOINT_X_LANTIQ_COM_VENDOR_HS20_OSUPROVIDERS_OSUPROVIDERFRIENDLYNAME2                                                                441
#define DEVICE_WIFI_ACCESSPOINT_X_LANTIQ_COM_VENDOR_HS20_OSUPROVIDERS_OSUPROVIDERNAI                                                                          442
#define DEVICE_WIFI_ACCESSPOINT_X_LANTIQ_COM_VENDOR_HS20_OSUPROVIDERS_OSUPROVIDERMETHODLIST                                                                   443
#define DEVICE_WIFI_ACCESSPOINT_X_LANTIQ_COM_VENDOR_HS20_OSUPROVIDERS_OSUPROVIDERICON                                                                         444
#define DEVICE_WIFI_ACCESSPOINT_X_LANTIQ_COM_VENDOR_HS20_OSUPROVIDERS_OSUPROVIDERICON2                                                                        445
#define DEVICE_WIFI_ACCESSPOINT_X_LANTIQ_COM_VENDOR_HS20_OSUPROVIDERS_OSUPROVIDERSERVICEDESCRIPTION                                                           446
#define DEVICE_WIFI_ACCESSPOINT_X_LANTIQ_COM_VENDOR_HS20_OSUPROVIDERS_OSUPROVIDERSERVICEDESCRIPTION2                                                          447
#define DEVICE_WIFI_ACCESSPOINT_X_LANTIQ_COM_VENDOR_HS20_L2FIREWALL                                                                                           448
#define DEVICE_WIFI_ACCESSPOINT_X_LANTIQ_COM_VENDOR_HS20_L2FIREWALL_ACTION                                                                                    449
#define DEVICE_WIFI_ACCESSPOINT_X_LANTIQ_COM_VENDOR_HS20_L2FIREWALL_INGRESSINTERFACE                                                                          450
#define DEVICE_WIFI_ACCESSPOINT_X_LANTIQ_COM_VENDOR_HS20_L2FIREWALL_EGRESSINTERFACE                                                                           451
#define DEVICE_WIFI_ACCESSPOINT_X_LANTIQ_COM_VENDOR_HS20_L2FIREWALL_PROTOCOL                                                                                  452
#define DEVICE_WIFI_ACCESSPOINT_X_LANTIQ_COM_VENDOR_HS20_L2FIREWALL_SOURCEMAC                                                                                 453
#define DEVICE_WIFI_ACCESSPOINT_X_LANTIQ_COM_VENDOR_HS20_L2FIREWALL_DESTINATIONMAC                                                                            454
#define DEVICE_WIFI_ACCESSPOINT_X_LANTIQ_COM_VENDOR_HS20_L2FIREWALL_PACKETTYPE                                                                                455
#define DEVICE_WIFI_ACCESSPOINT_X_LANTIQ_COM_VENDOR_HS20_L2FIREWALL_SOURCEIP                                                                                  456
#define DEVICE_WIFI_ACCESSPOINT_X_LANTIQ_COM_VENDOR_HS20_L2FIREWALL_DESTINATIONIP                                                                             457
#define DEVICE_WIFI_ACCESSPOINT_X_LANTIQ_COM_VENDOR_HS20_L2FIREWALL_SOURCEPORT                                                                                458
#define DEVICE_WIFI_ACCESSPOINT_X_LANTIQ_COM_VENDOR_HS20_L2FIREWALL_DESTINATIONPORT                                                                           459

OBJS_SUPPORTED = {
	"Device.WiFi",
	"Device.WiFi.Radio",
	"Device.WiFi.Radio.X_LANTIQ_COM_Vendor",
	"Device.WiFi.Radio.X_LANTIQ_COM_Vendor.WaveDriverStream",
	"Device.WiFi.Radio.X_LANTIQ_COM_Vendor.WaveConfigurationStream",
	"Device.WiFi.Radio.X_LANTIQ_COM_Vendor.WaveHostapdStream",
	"Device.WiFi.Radio.X_LANTIQ_COM_Vendor.WaveFwStream",
	"Device.WiFi.Radio.Stats",
	"Device.WiFi.NeighboringWiFiDiagnostic",
	"Device.WiFi.NeighboringWiFiDiagnostic.Result",
	"Device.WiFi.SSID",
	"Device.WiFi.SSID.Stats",
	"Device.WiFi.AccessPoint",
	"Device.WiFi.AccessPoint.Security",
	"Device.WiFi.AccessPoint.WPS",
	"Device.WiFi.AccessPoint.AssociatedDevice",
	"Device.WiFi.AccessPoint.AssociatedDevice.X_LANTIQ_COM_Vendor",
	"Device.WiFi.AccessPoint.AssociatedDevice.Stats",
	"Device.WiFi.AccessPoint.AC",
	"Device.WiFi.AccessPoint.AC.Stats",
	"Device.WiFi.AccessPoint.X_LANTIQ_COM_Vendor",
	"Device.WiFi.AccessPoint.X_LANTIQ_COM_Vendor.Security",
	"Device.WiFi.AccessPoint.X_LANTIQ_COM_Vendor.WPS",
	"Device.WiFi.AccessPoint.X_LANTIQ_COM_Vendor.AC",
	"Device.WiFi.AccessPoint.X_LANTIQ_COM_Vendor.HS20",
	"Device.WiFi.AccessPoint.X_LANTIQ_COM_Vendor.HS20.OperatorFriendlyName",
	"Device.WiFi.AccessPoint.X_LANTIQ_COM_Vendor.HS20.VenueName",
	"Device.WiFi.AccessPoint.X_LANTIQ_COM_Vendor.HS20.RoamingConsortium",
	"Device.WiFi.AccessPoint.X_LANTIQ_COM_Vendor.HS20.ConnectionCapability",
	"Device.WiFi.AccessPoint.X_LANTIQ_COM_Vendor.HS20.NAIrealm",
	"Device.WiFi.AccessPoint.X_LANTIQ_COM_Vendor.HS20.WanMetrics",
	"Device.WiFi.AccessPoint.X_LANTIQ_COM_Vendor.HS20.OSUicons",
	"Device.WiFi.AccessPoint.X_LANTIQ_COM_Vendor.HS20.OSUproviders",
	"Device.WiFi.AccessPoint.X_LANTIQ_COM_Vendor.HS20.L2Firewall",
};